### ISSUE TITLE
Double webdav url/path before creating directory

### ISSUE THREAD

**Issue by codepushr** [perry-mitchell/webdav-client#100]
So, I'm not sure if this is WebDAV related or related to this library but the `createDirectory()` method isn't working right for me.
In fact it's using the base path 2 times in a row, so basically this setup will result into:
```
var client = webdav(`http://foo.bar/remote.php/dav/files/root`)
client.createDirectory('com').then()

==> "MKCOL","url":"\/remote.php\/dav\/files\/root\/remote.php\/dav\/files\/root\/com"
```
I now have to hack it and use 4x "../" to make it work:
```
client.createDirectory('../../../../com').then()
```
Can anyone look into this?

**Comment by perry-mitchell** [comment]
Hi,

Is that really the root of your WebDAV service? This client works by tracking the root of your server with the full paths that the server returns. There’s possibly some bug with the repeated path, but first we need to discern what the root of your server is in case you’re specifying a sub directory in your connection URL..

**Comment by codepushr** [comment]
Hi, 

I believe it is, please correct me if I'm wrong. It's Nextcloud 13.0, so apparently the URL should be like this:
`example.com/nextcloud/remote.php/dav/files/USERNAME/`

(according to https://docs.nextcloud.com/server/13/user_manual/files/access_webdav.html)
