### ISSUE TITLE
webdav throws self.fetch.bind error on iOS

### ISSUE THREAD

**Issue by ammannbe** [perry-mitchell/webdav-client#113]
I've created an Ionic 3 App and want to use WebDAV to connect with my server.
When I want to access the module and start the App on an iOS device, I get following error:
`undefined is not an object (self.fetch.bind)`

I access the module following way:
```
import * as WebDAV from 'webdav';

@Component({
    selector: 'page-login',
    templateUrl: 'login.html'
})

export class LoginPage {

    cunstructor() {
        var webdav = WebDAV;  // On this code snippet the error appears
    }
}
```

I've found out, that the error happens in the module node-fetch/browser.js:
```
"use strict";

module.exports = exports = self.fetch;

// Needed for TypeScript and Webpack
exports.default = self.fetch.bind(self);

exports.Headers = self.Headers;
exports.Request = self.Request;
exports.Response = self.Response;
```

I couldn't figure out any solution or workaround and I'm not sure if this only related to node-fetch or also to the webdav module.

**Comment by perry-mitchell** [comment]
Hi @ammannbe - Sorry for the long delay.

I also use this in a mobile app (react-native), and have been seeing this error recently. I'll be removing `node-fetch` and will be replacing it with `axios`, so hopefully this issue will go away. Check out v2: #114

**Comment by ammannbe** [comment]
@perry-mitchell Thank you very much for that!

I've tested it with v2 and I can import the webdav module now.
But now when I try to create a client:
```
import * as WebDAV from 'webdav';

@Component({
    selector: 'page-login',
    templateUrl: 'login.html'
})

export class LoginPage {

    cunstructor() {
        var webdav = WebDAV.createClient(
                                "https://webdav.example.com",
                                username,
                                password,
        );
        webdav.getDirectoryContents(path)
                .then(function(contents) {
                    console.log(contents);
                });
    }
}
```
But now get following error:
```
Access to XMLHttpRequest at 'https://webdav.example.com/' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by perry-mitchell** [comment]
Well CORS can’t be bypassed in the browser - it’s a security feature. There’s nothing to my knowledge that I can do in WebDAV that will fix such a restriction. It’s a limitation set by the remote server.

**Comment by ammannbe** [comment]
Yes I've tested it on an Android emulator and device and get this error.

With the version 1.6.1 I can list directory content without problem. With v2 I get the CORS error.
I'm not sure if it's because of the `node-fetch` - `axios` change or if I've done something different...

**Comment by perry-mitchell** [comment]
I just pushed 74f18ed81bc5e71f8c30445a7aa241f640dbcf27 which should add support for CORS, but you need to pass the option `{ withCredentials: true }` to the method you're using.

For example:

```javascript
client.getDirectoryContents("/", { withCredentials: true });
```

**Comment by perry-mitchell** [comment]
@ammannbe Have you had any chance to test this? I'll be pushing a pre-release version to npm soon so you can also try that.

**Comment by perry-mitchell** [comment]
Please test version 2.0.0-rc1 which is now on npm.

**Comment by ammannbe** [comment]
Hi @perry-mitchell 

Sorry for late response - currently lot of work to do..
I'll test the rc1 today and/or tomorrow (then I've access to the server side and better debugging).

I think this should fix `Access-Control-Allow-Origin` on Android and iOS (not Browser)?

**Comment by ammannbe** [comment]
On Android with version 2.0.0-rc1 I get still following error
```
localhost/:1 XMLHttpRequest cannot load https://webdav.example.ch/. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 401.
vendor.js:1823 ERROR Error: Uncaught (in promise): Error: Network Error
Error: Network Error
    at createError (vendor.js:82959)
    at XMLHttpRequest.handleError [as __zone_symbol__ON_PROPERTYerror] (vendor.js:82842)
    at XMLHttpRequest.H (polyfills.js:3)
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (vendor.js:5125)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at e.invokeTask [as invoke] (polyfills.js:3)
    at p (polyfills.js:2)
    at XMLHttpRequest.v (polyfills.js:2)
    at createError (vendor.js:82959)
    at XMLHttpRequest.handleError [as __zone_symbol__ON_PROPERTYerror] (vendor.js:82842)
    at XMLHttpRequest.H (polyfills.js:3)
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (vendor.js:5125)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at e.invokeTask [as invoke] (polyfills.js:3)
    at p (polyfills.js:2)
    at XMLHttpRequest.v (polyfills.js:2)
    at c (polyfills.js:3)
    at c (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (vendor.js:5125)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at o (polyfills.js:3)
    at e.invokeTask [as invoke] (polyfills.js:3)
    at p (polyfills.js:2)
```

I'm not really sure if I import the module correctly. If I do it as in the docs  described (under **Usage**) I get `createClient is not a function`
With following, the error `createClient is not a function` disappears:
```
this.WebDAV = require('webdav');
var client = this.WebDAV.createClient(
    "https://webdav-server.org/remote.php/webdav",
    "username",
    "password"
);
```

**Comment by perry-mitchell** [comment]
Did you use the `withCredentials` option?

You can use it like:

```javascript
client.getDirectoryContents("/", { withCredentials: true });
```

**Comment by ammannbe** [comment]
> Did you use the `withCredentials` option?
> 
> You can use it like:
> 
> ```js
> client.getDirectoryContents("/", { withCredentials: true });
> ```

Yes I tried with and without. Same result.
