### ISSUE TITLE
Cannot get file content with Nextcloud

### ISSUE THREAD

**Issue by dlazzy** [perry-mitchell/webdav-client#115]
Hello,

Everythings work (1.6.1), *getDirectoryContents* is working well. But when I try to get file content, like a mp3 file on my Nextcloud :

```
client
      .getFileContents(path)
      .then((data) => {
        fs.writeFileSync("./test.mp3", data);
        return result(data);
      })
      .catch(() => {
        return result(false);
      });
```

The `test.mp3` created have a size of 114 bytes and containing `This is the WebDAV interface. It can only be accessed by WebDAV clients such as the Nextcloud desktop sync client.` So I don't understand why listing directories works but not getting file content.

**Comment by perry-mitchell** [comment]
@dlazzy What is the format of the URL you're using? It may be that you're requesting the wrong path. If you share the URL, just obscure the domain.

For example, if I create a demo account at [demo.nextcloud.com](demo.nextcloud.com), I get a URL like this: `https://demo.nextcloud.com/eav0thai/`. Fetching from `https://demo.nextcloud.com/eav0thai/remote.php/webdav` should work, if you enter that as the client URL.

It should be available from the settings in the bottom left:

![image](https://user-images.githubusercontent.com/3869469/48371994-ea616f80-e6c5-11e8-8ea1-3187601ee8b8.png)

**Comment by dlazzy** [comment]
@perry-mitchell I use the URL given by Nextcloud at the bottom left :

```text
https://sub.domain.com/remote.php/webdav/
```

Using this I can get directories content, and also explore the Nextcloud using Ubuntu explorer using davfs:// and by providing my credentials. Also, with the Ubuntu explorer I can play music from the webdav. The main problem is I don't know where to start to debug this :confused:

**Comment by perry-mitchell** [comment]
Well you could try to use a tool like [Postman](https://www.getpostman.com/) to make the request you are and see what it returns. If you jump into the `node_modules/webdav` contents and edit the main file in `dist/`, you should be able to do some logging. You could also use [node's `--inspect`](https://nodejs.org/api/debugger.html) option, which might be an even better option. Check out the network request and replicate that in Postman.

Ideally you want to find out where the error is coming from - this library or your server.

**Comment by dlazzy** [comment]
Thanks for your advice, but I can't get how to correctly debug within your packages.
For example in request.js I've put a `console.log(url, options)` and this throw me a :
```text
https://domain.com/remote.php/webdav/Playlists { method: 'GET',
  headers: { Authorization: 'Basic YWRtaW46VmFsZW50aW40NQ==' },
  agent: undefined }
Promise { <pending> }
```
I don't understand, but when I call a music url, in my case the url should be `https://domain.com/remote.php/webdav/Playlists/CH3SHIRE%20-%20Primal.mp3` here I don't see the music name :thinking:

**Comment by dlazzy** [comment]
The URL requested is : `https://domain.com/remote.php/webdav/Playlists/CH3SHIRE%20-%20Primal.mp3` the url I see through the **console.log** is : `https://domain.com/remote.php/webdav/Playlists`

From my simple .html I call this URL : https://domain.com/music/CH3SHIRE%20-%20Primal.mp3 then under Express, I will use your package to call the webdav URL, the music name is a request params and then I build the webdav url. This works when listing directories and it's content.

**Comment by perry-mitchell** [comment]
Ok, thanks for clearing that up. So you're using it from node to download a file that was requested from a web client against your express server.

* Website req: `https://domain.com/music/CH3SHIRE%20-%20Primal.mp3`
* Server -> Server req: `https://domain.com/remote.php/webdav/Playlists/CH3SHIRE%20-%20Primal.mp3`

And you're confirming that the response is still broken, returning text?

**Comment by dlazzy** [comment]
I confirm this behavior :

On my Express server I have a route that handle user asking to see what's inside a folder :
```js
let client = webdav(
    config.webdav.url,
    config.webdav.username,
    config.webdav.password
  );

  client
    .getDirectoryContents(req.body.path ? config.webdav.basePath + '/' + req.body.path : config.webdav.basePath)
    .then((result) => {
      let folders = [];
      let files = [];

      if (result.length) {
        folders = result.filter(y => y.type === 'directory');
        files = result.filter(y => y.mime === 'audio/mpeg');
      } else {
        folders = [];
        files = [];
      }

      console.log(result);
      return res.send({
        success: true,
        data: {
          folders: folders,
          files: files
        }
      });
    })
    .catch((err) => {
      res.status(500);

      return res.send({
        success: false,
        err: err
      });
    });
```

Then user click on a button `Play musics from this folder` if the folder contain .mp3 files, this redirect to a music player and show the musics list. When user choose a music this route is called :

```js
read: (username, password, url, path, result) => {
    let client = webdav(
      url,
      username,
      password
    );

    client
      .getFileContents(path)
      .then((data) => {
        return result(data);
      })
      .catch(() => {
        return result(false);
      });
    /*var stream = client.createReadStream(path);

    return result(stream)*/
  }
```
(route call the `read` function in an exported module then return .mp3 content)

I've made a video : <https://streamable.com/ee7oa> (I go to play-base route to show the root path musics because clicking on button 'play music from this folder' is not done for now)

**Comment by dlazzy** [comment]
You give me right direction :+1: 

Before I was saying :

> I don't understand, but when I call a music url, in my case the url should be https://domain.com/remote.php/webdav/Playlists/CH3SHIRE%20-%20Primal.mp3 here I don't see the music name thinking

My fault, maybe I should post the route entirely. The route was configured like this before :

```js
router.get('/music/:id*', (req, res) => {
// Working to get music
});
```

But the `*` don't work, if there is slash in url it will stop at the first slash. Now I set `'/music/:id(*)'` and this is working well ! Now musics can be read, thank you very much for your help !

**Comment by perry-mitchell** [comment]
Hey that's excellent news @dlazzy! I'm happy to hear that it's working for you. I appreciate your patience in working through this. 

I'll close this now.
