### ISSUE TITLE
Options - Param for all Methods

### ISSUE THREAD

**Issue by balu-** [perry-mitchell/webdav-client#12]
It would be good to be able to submit additional parameters for a request (for example special headers, or parameters like `overwrite`). 
Therefor it would be best to have an options param at all request methods [ like in the `putFileContents`method ].
This change (extending functions by a param) should be uncritical cause if it is omited default values will be used, so that functions behave like before.

**Comment by perry-mitchell** [comment]
Agreed. Will check further when I'm in front of a computer. Thanks.
