### ISSUE TITLE
glob like functionality would be handy

### ISSUE THREAD

**Issue by tansaku** [perry-mitchell/webdav-client#122]
on a local file system one can use a library like glob to get all the files matching a particular pattern

https://github.com/isaacs/node-glob#readme

being able to do over webdav would be handy, although clearly some patterns could be very time consuming to match ...

**Comment by perry-mitchell** [comment]
I like this idea.. I also think it'd be very useful.

Are you thinking that such functionality would be just used to return a list of files?

For instance: `client.glob("/dir/**/*.mp4")` :

```
/dir/test.mp4
/dir/sub/dir/video.mp4
/dir/dir/movie.mp4
```

**Comment by tansaku** [comment]
@perry-mitchell yes, exactly

**Comment by perry-mitchell** [comment]
@tansaku Any opinion on the function name? I was thinking along the following lines, but don't have a hard opinion on the subject as of yet:

 * `glob`
 * `getPaths`
 * `getFilenames`

**Comment by tansaku** [comment]
@perry-mitchell I guess I'd go for glob, although it's not wonderfully self-explanatory https://en.wikipedia.org/wiki/Glob_(programming)

one can always have additional alternative function names that map to the same thing.

**Comment by perry-mitchell** [comment]
Yeah in that way I'd personally opt for `getPaths` or something more descriptive.

**Comment by tansaku** [comment]
something like `allMatchingPaths` might be good ... something that indicates we are looking for matches ... maybe even `allPathsMatchingPattern`

there are various linters that push we away from using the get prefix, but `getPathsMatchingPattern` would fit in with the existing function names I guess ... although excessive perhaps if there is no alternate "non-matching" `getPaths` function ...

**Comment by perry-mitchell** [comment]
I hear you.. Is `getMatchingPaths` too brief? I do like the `get` prefix as it indicates that an action will take place. `all...` sounds too passive for my taste as it just sounds like a getter.

At least we agree that this function would be super helpful, regardless of what the name may be.

**Comment by tansaku** [comment]
`getMatchingPaths` just fine :-)

**Comment by perry-mitchell** [comment]
Released in 2.6.0.

I converted `{ glob: { pattern: "..." } }` to `{ glob: "..." }` for simplicity. Thanks everyone.
