### ISSUE TITLE
test/testContents and test/serverContents seem very similar

### ISSUE THREAD

**Issue by tansaku** [perry-mitchell/webdav-client#123]
Is one of `test/testContents` and `test/serverContents` redundant?  Do they both have an important role? 

I can see both being referred to in the code base, but also that `test/testContents` is in .gitignore ...

**Comment by perry-mitchell** [comment]
`testContents` is wiped for a bunch of tests and replaced with the contents of `serverContents`. I'm sure this could be handled better but I haven't gone out of my way to streamline it as it's been working well.

Do you have a better suggestion?

**Comment by perry-mitchell** [comment]
I'll close this - `testContents` is not committed, and shouldn't be regarding as being part of the project structure that's visible in this repo. Happy to have it renamed however, if someone wants to make a PR.

**Comment by tansaku** [comment]
@perry-mitchell - something I'm trying in another project is git clean to revert dirs ...
