### ISSUE TITLE
naming and other minor issues in test/server/index.js

### ISSUE THREAD

**Issue by tansaku** [perry-mitchell/webdav-client#124]
I was just setting up test/server/index.js in another project to have a webdav server for tests and I noticed some minor things that might be helpful, or not :-)

[test/server.index.js](https://github.com/perry-mitchell/webdav-client/blob/master/test/server/index.js#L49) has the following:

```js
createServer.webdavClient = function(authType) {
    return createServer(path.resolve(__dirname, "../testContents"), authType);
};
```
and I think that this might be better as:

```js
createServer.webdavServer = function(authType) {
    return createServer(path.resolve(__dirname, "../testContents"), authType);
};
```
because it is a server being created here right? not a client?

If we changed that would lead to a corresponding change in [test/specs/index.js](https://github.com/perry-mitchell/webdav-client/blob/master/test/specs/index.js#L6)

```js
const createWebDAVServer = baseWebDAVServer.webdavServer;
```

and similarly in [test/web/server.js](https://github.com/perry-mitchell/webdav-client/blob/master/test/web/server.js#L7)

I think that's the only two places it's being referred to ...

**Comment by tansaku** [comment]
and running the server locally I was seeing output like:

```
Created server on with config: 9988 undefined
```
from the [following](https://github.com/perry-mitchell/webdav-client/blob/master/test/server/index.js#L23):

```js
console.log("Created server on with config:", 9988, authType);
```
which I thought could be improved to:

```js
console.log(`Created server on localhost with port: 9988, and authType: ${authType}`);
```

**Comment by tansaku** [comment]
let me know what you think - could put in some PRs if you were interested in these sorts of changes ...

**Comment by perry-mitchell** [comment]
I like this idea! Go ahead @tansaku I'd really appreciate it 👍
