### ISSUE TITLE
Return values of getRequests should be an Object with a content Field instead of pure content-value

### ISSUE THREAD

**Issue by balu-** [perry-mitchell/webdav-client#13]
Return values of `getRequests` should be an Object with a content Field instead of pure content-value.
If the `getRequest`-Methodes return an object like 
```
{
     content: <value>
}
```
instead of `<value>`, additional return values may be provided (like response headers).
Such addional values may be `requested` via the options param (see #12 ).

This change would break backwards compatibility.
Alternatively new function-names may be used for this `new return method`, so that compatibility is granted.

**Comment by perry-mitchell** [comment]
Requires huge API changes - moved to **2.0.0**.
