### ISSUE TITLE
getDirectoryContents: etags in resulting entries

### ISSUE THREAD

**Issue by skoschik** [perry-mitchell/webdav-client#132]
It would be really helpful to have the etags in the propfind responses.  It makes for a quick way to see changes across a lot of files/directories in one shot.  Used in conjunction with the depth header = 'infinite' it's a nice way to only pick out changes without blasting the server with individual requests for things that may not have changed.

**Comment by perry-mitchell** [comment]
Sounds like a good idea. The property could be `etag` and it could default to `null`. This should be updated in the docs in the readme as well.
