### ISSUE TITLE
set lastmod when putting file contents

### ISSUE THREAD

**Issue by tansaku** [perry-mitchell/webdav-client#136]
Does this library (or indeed the webdav protocol itself?) support setting the lastmod time of a file when it's put to the webdav server?

Failing that, is there some way to add some meta-data to files uploaded in which one could store the last updated at time (from the local file system)?

I'm thinking about this in the context of syncing files.  If the lastmod on the server is the time the file was uploaded rather than the time it was updated on the local system, it's difficult to tell if there is a change on the server that needs pulling down or not ...

**Comment by tansaku** [comment]
looks like it can be done with nextcloud/webdav: https://medium.com/@mathiasconradt/how-to-assign-custom-meta-data-to-your-documents-on-nextcloud-23356cf3f926

**Comment by skoschik** [comment]
This library supports lastmod.  However, the last modified time for a file shouldn't be set by the client.  It's a property the server maintains, and for good cause. 
https://stackoverflow.com/questions/3579608/webdav-can-a-client-modify-the-mtime-of-a-file

Custom properties -meta-data- are valid within the webdav spec but it's not needed for a sync.
As far as syncing goes.  Have a look at [Etags](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag) . This library supports Etags as well.

**Comment by tansaku** [comment]
thanks @skoschik - I've got a passing familiarity with Etags - however I don't seem to be receiving any etag data back from nextcloud when getting Directory contents or stating individual files with the webdav client:

```
Promise {
  [ { filename: '/projects/active/2019-01-29.17112.proj',
    basename: '2019-01-29.17112.proj',
    lastmod: 'Tue, 29 Jan 2019 11:33:15 GMT',
    size: 4704,
    type: 'file',
    mime: 'application/octet-stream' },
```

I guess that's on nextCloud ...

**Comment by tansaku** [comment]
ah, I was on the old version - working now ... and I see that nextCloud is putting random numbers in the Etag fields that are guaranteed to change when the file changes: https://docs.nextcloud.com/desktop/2.3/architecture.html#synchronization-by-time-versus-etag
