### ISSUE TITLE
Response headers with createReadStream

### ISSUE THREAD

**Issue by Paxa** [perry-mitchell/webdav-client#142]
Is it possible to get response headers when using `createReadStream` method?

As I see in `createStream.js`:
```js
return request(requestOptions).then(responseHandlers.handleResponseCode).then(res => res.data);
```
`.then(res => res.data)` - this makes possible to access only body

**Comment by perry-mitchell** [comment]
I'll definitely add a method for making this easier, like a promise-based `getReadStream()` that will resolve with the stream and headers.
