### ISSUE TITLE
SSO with SAML, Keycloak and Nextcloud

### ISSUE THREAD

**Issue by brenopolanski** [perry-mitchell/webdav-client#145]
I'm using an SSO with SAML, [Keycloak](https://www.keycloak.org/) + Nextcloud and I tried use of WebDAV client to connect to it using [AuthToken](https://github.com/perry-mitchell/webdav-client/blob/master/API.md#authtoken--object):

```javascript
  async componentWillMount() {
    const { user } = this.props.auth;

    const client = createClient(
      'https://address.com',
      {
        token: {
          access_token: user.token,
          token_type: 'Bearer'
        }
      }
    );

    const directoryItems = await client.getDirectoryContents('/');
  }
```

and it returned:

![screenshot from 2019-02-06 19-55-56](https://user-images.githubusercontent.com/1894191/52380722-b2ac5e80-2a4d-11e9-8dd1-7e7d6fe866ab.png)

Someone already managed to use the WebDAV client connecting on Nextcloud using Keycloak?

**Comment by brenopolanski** [comment]
Problem solved here: https://github.com/nextcloud/server/issues/5512

**Comment by zahradehghanpur** [comment]
what did you do exactly to solve your problem?
