### ISSUE TITLE
Chrome: Refused to set unsafe header "Content-length"

### ISSUE THREAD

**Issue by SpudNyk** [perry-mitchell/webdav-client#150]
When uploading a file in chrome (putFileContent), I get 'Refused to set unsafe header "Content-length"' in the browser console.

**Comment by perry-mitchell** [comment]
Yes, this seems to be a problem with many utilities recently I've found. I've been playing a bit with another app and request client entirely and see the same issue in Chrome when sending multipart requests to Google drive. It's not break anything of course, just ugly. Not sure if we have any control over this? Maybe axios has some option.

**Comment by SpudNyk** [comment]
`client.putFileContents` explicitly sets the content-length to the `length` property of what was passed in.

A little off topic but this behavior means any `File` (from browser file input fields) or `Blob` browser objects have to have a `length` property added (they have a `size` property instead), for the library to behave as designed. The library does upload them just fine though.

**Comment by skoschik** [comment]
It looks like Axios sets "Content-Length" header automatically.

https://github.com/axios/axios/blob/master/lib/adapters/http.js#L55

Wondering if client.putFileContents needs to set "Content-Length" at all.  I haven't done any testing without it but looking at the Axios source it's probably worth a shot.

**Comment by perry-mitchell** [comment]
This is not uncommon:
 * https://github.com/mjackson/http-client/issues/35
 * https://community.dynamics.com/crm/f/117/t/228330
 * https://stackoverflow.com/questions/7210507/ajax-post-error-refused-to-set-unsafe-header-connection/7210840

Seems the only action to take is to not set this in the browser. Other platforms are fine. We need to find a clean way to disable this in the browser, but please remember that this is not in fact in error (to my knowledge).. the request still goes through.

**Comment by perry-mitchell** [comment]
Now configurable via `options.contentLength` on `putFileContents`.
