### ISSUE TITLE
createClient is not a function

### ISSUE THREAD

**Issue by dekimpeb** [perry-mitchell/webdav-client#153]
Hi,

Whenever I try to use this, I get the following error:
`var client = createClient(
             ^

TypeError: createClient is not a function
    at Object.<anonymous> (C:\Users\Bart\Documents\Projects\ssh2\app.js:20:14)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3`

Here is my code:
`var createClient = require("webdav");
 
var client = createClient(
    "https://url/remote.php/webdav/",
    "username",
    "password"
);
 
client
    .getDirectoryContents("/")
    .then(function(contents) {
        console.log(JSON.stringify(contents, undefined, 4));
    });`

**Comment by jbruni** [comment]
@dekimpeb - Your code would work in older versions of `webdav-client`, because the `require` command imported the `createClient` function.

At current `webdav-client` version, `require` imports an object with a number of functions, one of them being `createClient`.

You can do:

```js
var createClient = require("webdav").createClient;
```

or (using modern syntax):

```js
const { createClient } = require("webdav");
```

**Comment by dekimpeb** [comment]
Thanks, but then I receive another error:
`(node:10384) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Request failed with status code 401
(node:10384) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

And when I do the exact example as described in the readme, I get:
`const directoryItems = await client.getDirectoryContents("/");
                       ^^^^^

SyntaxError: await is only valid in async function
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:605:28)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3`

**Comment by jbruni** [comment]
@dekimpeb - This is not a problem with the library, but with modern JavaScript usage.

Indeed, `await` keyword can only be used within an `async` function.

Here is one possible way to do it from outside a function, or from a non-async function:

```js
client.getDirectoryContents("/").then(function (directoryItems) {
    // use directoryItems here
}).catch(function (error) {
    // handle error here
});
```

HTTP status code 401 means is the **Unauthorized** status code. It indicates that "the request has not been applied because it lacks valid authentication credentials for the target resource" (see https://httpstatuses.com/401).

The "UnhandledPromiseRejectionWarning" means that there no `catch` block was found to handle a rejected promise. In this case, the promise has been rejected due to the HTTP authorization error 401.

**Comment by dekimpeb** [comment]
But why do I succesfully retrieve the XML when I only do it with the exact same username & password when using XHR?
`var XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;
var xhr = new XMLHttpRequest();

const url='**url**';

xhr.open("PROPFIND", url, true, "**username**", "**password**!");
xhr.setRequestHeader('Depth', '1');
xhr.withCredentials = 'true';
xhr.send();
xhr.onreadystatechange=(e)=>{
    console.log(xhr.responseText);
}`

**Comment by jbruni** [comment]
@dekimpeb - Maybe you are using the old `createClient` syntax.

Old syntax:

```js
var client = createClient(
    "https://example.com/webdav/",
    "myusername",
    "mypassword"
);
```

If this is the case, try using the new syntax instead.

New syntax:

```js
var client = createClient(
    "https://example.com/webdav/",
    {
        username: "myusername",
        password: "mypassword"
    }
);
```

**Comment by dekimpeb** [comment]
Nope, using the new synta
``const { createClient } = require("webdav");

const client = createClient(
    "url",
    {
        username: "",
        password: "!"
    }
);``

**Comment by dekimpeb** [comment]
> @dekimpeb - Maybe you are using the old `createClient` syntax.
> 
> Old syntax:
> 
> ```js
> var client = createClient(
>     "https://example.com/webdav/",
>     "myusername",
>     "mypassword"
> );
> ```
> 
> If this is the case, try using the new syntax instead.
> 
> New syntax:
> 
> ```js
> var client = createClient(
>     "https://example.com/webdav/",
>     {
>         username: "myusername",
>         password: "mypassword"
>     }
> );
> ```

**Comment by jbruni** [comment]
@dekimpeb - I've done a quick research and found that the "username" and "password" you pass to `xhr.open` are used in the request **URL**. The "username" and "password" provided to `webdav-client` are used to create an Authentication **header**.

So... this is how you should be creating the WebDAV client instance. You only need the URL parameter:

```js
const { createClient } = require("webdav");

const client = createClient("https://username:password@url/remote.php/webdav/");
```

**Comment by perry-mitchell** [comment]
Yes, we deprecated the URL based authentication a while back for obvious reasons. Besides being thoroughly insecure, passwords containing special characters break the request.
