### ISSUE TITLE
[BUG] [HELP NEEDED] Maximum call stack error 

### ISSUE THREAD

**Issue by ubarsaiyan** [perry-mitchell/webdav-client#156]
Hi,

I am using this npm library to connect to webdav via username and password and it seemed to be working fine. But as I was switching to authorization using OAuth, I discovered a bug. If I enter wrong username password combination, the server crashes with the following error: 

```
RangeError: Maximum call stack size exceeded
W20190504-19:52:30.554(5.5)? (STDERR)     at Array.forEach (<anonymous>)
W20190504-19:52:30.557(5.5)? (STDERR)     at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
W20190504-19:52:30.561(5.5)? (STDERR)     at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
W20190504-19:52:30.561(5.5)? (STDERR)     at Array.forEach (<anonymous>)
W20190504-19:52:30.561(5.5)? (STDERR)     at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
W20190504-19:52:30.562(5.5)? (STDERR)     at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
W20190504-19:52:30.562(5.5)? (STDERR)     at Array.forEach (<anonymous>)
W20190504-19:52:30.562(5.5)? (STDERR)     at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
W20190504-19:52:30.562(5.5)? (STDERR)     at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
...
```

Here is my code:
```
Meteor.methods({
	async addWebdavAccount(formData) {

		const userId = Meteor.userId();

		if (!userId) {
			throw new Meteor.Error('error-invalid-user', 'Invalid User', { method: 'addWebdavAccount' });
		}

		if (!settings.get('Webdav_Integration_Enabled')) {
			throw new Meteor.Error('error-not-allowed', 'WebDAV Integration Not Allowed', { method: 'addWebdavAccount' });
		}

		check(formData, Match.ObjectIncluding({
			serverURL: String,
			username: String,
			pass: String,
		}));

		const client = createClient(
			formData.serverURL,
			{
				username: formData.username,
				password: formData.pass,
			}
		);

		try {
			await client.stat('/');
		} catch (error) {
			return { success: false, message: 'could-not-access-webdav', error };
		}

		const accountData = {
			user_id: userId,
			server_url: formData.serverURL,
			username: formData.username,
			password: formData.pass,
			name: formData.name,
		};
		try {
			WebdavAccounts.insert(accountData);
			return { success: true, message: 'webdav-account-saved' };
		} catch (error) {
			return { success: false, message: error.code === 11000 ? 'duplicated-account' : 'unknown-write-error', error };
		}

	},
});

```

Thanks for your help. :)

**Comment by ubarsaiyan** [comment]
This is  what the `getStat` function of your library gets as the second argument. Is this correct? 
```
I20190505-00:53:14.671(5.5)? { headers: 
I20190505-00:53:14.672(5.5)?    { Authorization: 'Bearer X57WhOSmgp7rLJ2GfdkjsomemorecharactershereoMz0yAf2f5FdXYub' },
I20190505-00:53:14.672(5.5)?   remotePath: '/remote.php/webdav',
I20190505-00:53:14.672(5.5)?   remoteURL: 'https://nextcloud-fi.webo.hosting/remote.php/webdav/',
I20190505-00:53:14.672(5.5)?   httpAgent: undefined,
I20190505-00:53:14.672(5.5)?   httpsAgent: undefined }
```

**Comment by perry-mitchell** [comment]
I'm not sure what's causing your issue, but it doesn't seem to be with webdav-client. The package EJSON (in your trace) is not used by this library.

Also, the stat call you're making doesn't do anything. Should it be returned?

If you could share an example script that causes the error on it's own without meteor or any other external framework, I could debug based upon that. If it doesn't reproduce in a sterile environment again, it's most definitely not webdav-client.

**Comment by ubarsaiyan** [comment]
@perry-mitchell thank you for your support. The stat call checks whether or not the client can connect to webdav. If it cannot it throws an error which is caught by the try catch block. I also think now that the problem may not be with the library. Hence, I'll close the issue. However, can you please tell me one thing... If the authentication credentials are wrong will the library throw an error? And what is the correct way to test whether or not the client could connect to the server. Thank you. 😀

**Comment by perry-mitchell** [comment]
@ubarsaiyan It will throw an error if the credentials are wrong, and that error should have a HTTP `status` property. If that's say `401` then it was an authorisation error.
