### ISSUE TITLE
bind folder

### ISSUE THREAD

**Issue by wormen** [perry-mitchell/webdav-client#157]
After initializing the connection, how can I associate a remote directory with a local one?

**Comment by perry-mitchell** [comment]
How do you mean associate? There's no sync'ing provided by default, though I've considered adding such functionality. All commands in this library are active - you need to call them to transfer something, delete something, move something etc.

**Comment by perry-mitchell** [comment]
I'm working on sync support in the background at the moment, so sync'ing will be possible in the future. Closing in favour of #160.
