### ISSUE TITLE
missing status code in exceptions in browser

### ISSUE THREAD

**Issue by Shekesh** [perry-mitchell/webdav-client#159]
Hello @perry-mitchell,

when I use your library in the browser and an exception for like 404 or 401 is thrown, it's not the exception you're creating in 
[https://github.com/perry-mitchell/webdav-client/blob/d8cd0c65a021f9361e7b3886adb25a9a3607c648/source/response.js#L3-L12](https://github.com/perry-mitchell/webdav-client/blob/d8cd0c65a021f9361e7b3886adb25a9a3607c648/source/response.js#L3-L12)

It seems like axios is creating an error beforehand and throws that one.
As a result I don't get the `status` as a field which I need to have a clean error handling depending on the http response code. And I don't want to depend on parsing the returned error message where might or might not be the code included.

example
```
try {
	const client = createClient('http://localhost:1234/');
	await client.stat('whatever');
}
catch (error) {
	console.error(error);
}
```
result
```
Error: "Request failed with status code 404"
    createError /node_modules/axios/lib/core/createError.js:16
    settle /node_modules/axios/lib/core/settle.js:18
    handleLoad /node_modules/axios/lib/adapters/xhr.js:77
```

Catching that axios exception and handling it in the already existing handling function would be very helpful.

Thank you very much.

**Comment by perry-mitchell** [comment]
Good catch @Shekesh! Thanks for this 👍

**Comment by perry-mitchell** [comment]
This should be working now with `fetch` as the client.
