### ISSUE TITLE
Please update axios to 0.19

### ISSUE THREAD

**Issue by julijane** [perry-mitchell/webdav-client#161]
Please update axios to 0.19 to get this fix:

> Fix defaults to use httpAdapter if available (axios/axios#1285)
>> Fixing defaults to use httpAdapter if available
>> Use a safer, cross-platform method to detect the Node environment

The old code in the axios version currently used by webdav-client incorrectly chooses to use XMLHttpRequest in a mixed node/browser environment (e.g. electron, nwjs, testing environments). This is fixed in axios 0.19.

**Comment by perry-mitchell** [comment]
Thanks @julijane! This is fixed in 2.9.0
