### ISSUE TITLE
How to know whether connection is successful?

### ISSUE THREAD

**Issue by martingronlund** [perry-mitchell/webdav-client#163]
If I connect to an invalid url, how am I intended to find that out?

**Comment by perry-mitchell** [comment]
Well this would be possible to detect if the errors were correctly populated with error code information, which they are not. Pending this issue: https://github.com/perry-mitchell/webdav-client/issues/159

**Comment by perry-mitchell** [comment]
I’ll close this in favour of the aforementioned issue, but if you feel that the issue lies elsewhere I can reopen it.
