### ISSUE TITLE
Get file preview

### ISSUE THREAD

**Issue by ubarsaiyan** [perry-mitchell/webdav-client#164]
How do I get the file preview for Nextcloud? The GET request to be sent is of the format: `<nextcloud server>/core/preview?fileId=FILEID&x=256&y=256`. Or is there some functionality built in to send custom requests?

**Comment by perry-mitchell** [comment]
Hi @ubarsaiyan - This library provides a client for WebDAV resource requests, such as getting directory contents and downloading files - nothing more. Nextcloud is a spiced-up file storage solution which provides WebDAV connectivity - The WebDAV protocol, and thusly this library, have no knowledge of Nextcloud's extra functionality.

If Nextcloud provides some way to download these file previews you could simply make such requests using this library directly, but this library won't have any helper functions to locate these on a Nextcloud service. I'll close this issue as it's not related with the client itself.

Good luck looking in to this!

**Comment by ubarsaiyan** [comment]
@perry-mitchell Thank you for your insight. If I find a solution I'll write it here so that it can help others. Thanks :)

**Comment by perry-mitchell** [comment]
@ubarsaiyan That'd be great! Good luck

**Comment by ubarsaiyan** [comment]
@perry-mitchell I tried with the downloading the file preview through this library but I think it's not possible as the preview file I want is at a URL like `https://nextcloud.utkarshbarsaiyan.com/index.php/core/preview.png?file=/Nextcloud.png&x=256&y=256` but the url the `getFileContents` want is of the form `/Nextcloud.png`. Anyways, thank you. I'll try to send a get request manually.

**Comment by perry-mitchell** [comment]
@ubarsaiyan I might consider adding a custom request function so you could complete this yourself _using_ this library. Basically then `webdav` would handle authentication for you but allow you to request your own URLs and do your own result handling..

**Comment by ubarsaiyan** [comment]
@perry-mitchell that's a great idea. I think it can make this library much more powerful. If I can help in any way, do let me know :)

**Comment by perry-mitchell** [comment]
#169 will take care of the custom request functionality :)
