### ISSUE TITLE
Custom request API

### ISSUE THREAD

**Issue by perry-mitchell** [perry-mitchell/webdav-client#169]
Allow consumers of this library to make custom requests. Provide a request method that handles authentication but allows the consumer to specify the URL path, request headers and body. Provide helpers for parsing the result payload.

**Comment by ubarsaiyan** [comment]
@perry-mitchell I want to submit a PR for this. Can you please get me started? What set up is required for development and to get test the functionalities? I can use Nextcloud server as a WebDAV server. Sorry, couldn't find instructions in the CONTRIBUTING file.

**Comment by janswist** [comment]
Is there any chance for an example? I need to create custom request where I get first folder that meet conditions (for example: ends with 12345 number). Would love to be able to do this with your lib.

**Comment by perry-mitchell** [comment]
@janswist Right now [custom requests](https://github.com/perry-mitchell/webdav-client#custom-requests) require you to implement parsing logic by yourself, which would be quite complex. I'd recommend against it for directory lookups.

A less performance-friendly example could work like so:

```javascript
const contents = await client.getDirectoryContents("/", { deep: true });
const folder = contents.find(item => item.type === "directory" && /12345$/.test(item.basename));
```

I haven't tested this, but it should be quite close to what you might need. The `{deep:true}` option returns a flat array of all items.

**Comment by perry-mitchell** [comment]
It wouldn't be a bad idea to expose the parsing logic so that custom requests might be more useful, when combined with such helpers..

**Comment by janswist** [comment]
> @janswist Right now [custom requests](https://github.com/perry-mitchell/webdav-client#custom-requests) require you to implement parsing logic by yourself, which would be quite complex. I'd recommend against it for directory lookups.
> 
> A less performance-friendly example could work like so:
> 
> ```js
> const contents = await client.getDirectoryContents("/", { deep: true });
> const folder = contents.find(item => item.type === "directory" && /12345$/.test(item.basename));
> ```
> 
> I haven't tested this, but it should be quite close to what you might need. The `{deep:true}` option returns a flat array of all items.

I tested something very similar before, but yes - it's low-performant. It takes couple of seconds to get all the files AND then filter through them. I tried using glob, but then I got error - [link to issue here](https://github.com/perry-mitchell/webdav-client/issues/199). Can I ask for looking into it?

**Comment by perry-mitchell** [comment]
@janswist Yes let's continue in the other issue.
