### ISSUE TITLE
[HRLP NEEDED]how to move file whit different folder

### ISSUE THREAD

**Issue by twt898xu** [perry-mitchell/webdav-client#171]
Hi, I have a problem and need your help

physicalPath:
/workspace/usrRoot/rose
/workspace/usrRoot/share

weddavPath:
/webdav/rose
/webdav/rose/share 

The above physical path corresponds to the following webdavPath. How can I move the file under /workspace/usrRoot/rose/ below to  /workspace/usrRoot/share/  below?

**Comment by perry-mitchell** [comment]
Well this sounds quite confusing and a little counter intuitive.. but if that’s the mount then all I could suggest would be the following: move from `/webdav/rose/file.txt` to `/webdav/rose/share/file.txt`. The actual directories matter not and only the WebDAV structure is known to the WebDAV client.

**Comment by twt898xu** [comment]
Thank you
Maybe it's the configuration of the weddav service
move from _/webdav/rose/file.txt_ to  _/webdav/rose/share/file.txt_
http status code with 409

**Comment by perry-mitchell** [comment]
A 409 status is “conflict”, so there may already be a file with that name there.

**Comment by twt898xu** [comment]
Thank you
I solved this problem by changing the configuration of webdav
