### ISSUE TITLE
Missing Authorization-Header

### ISSUE THREAD

**Issue by RichardNutt** [perry-mitchell/webdav-client#172]
Hello,

I am currently trying to use the webdav client coupled with a nextcloud server in an Angular Project, but am unable to download files. I set up the client in the following way:
```typescript
import { Injectable } from '@angular/core';
import { AppConfig } from '../app-config/app-config';
import webdav from 'webdav';

@Injectable({
  providedIn: 'root'
})
export class BlobServiceService {

  private client: any;
  constructor() {
    this.client = webdav.createClient(
      "http://127.0.0.1/remote.php/dav/files/nextclouduser/",
      {
        username: "nextclouduser",
        password: "123456"
      }
    );
  }

  public async getFile(path: string): Promise<any> {
    return this.client.getFileContents(path);
  }
```
When calling `getFile("file")` an OPTIONS-Request gets send, but it is missing the Authorization-Header.

Request:
```
Host: 127.0.0.1
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Access-Control-Request-Method: GET
Access-Control-Request-Headers: authorization
Referer: http://localhost:4200/page/test
Origin: http://localhost:4200
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
```

Response:
```
HTTP/1.1 401 Unauthorized
Server: nginx/1.17.1
(...)
```
The request works fine once I add the Authorization-Header `Authorization: xxxxx` manually. I don't know if this is supposed to happen since I am still quite inexperienced, but I hope that someone can help me. :)

**Comment by perry-mitchell** [comment]
The options request is sent by the browser, not by the WebDAV client. OPTIONS requests are never sent with authorization and the server should never require it for options to be successful. If Nextcloud is indeed expecting it, then it is implemented incorrectly.

If it’s responding with a 401 in preflight then it’s most likely never going to work on local host. You may need to modify your server’s apache or nginx config to always send open CORS headers, as this is probably a CORS issue. Nextcloud is known to be extremely problematic in this regard.

**Comment by perry-mitchell** [comment]
You can check out the ongoing issue on their issue tracker: https://github.com/nextcloud/server/issues/3131

**Comment by RichardNutt** [comment]
Thank you. That answers my question :)
