### ISSUE TITLE
Suggestion: Respons Type as Blob

### ISSUE THREAD

**Issue by emreyigit** [perry-mitchell/webdav-client#175]
Hi everyone,

I have used the library. Then I realized that _getFileContents_ function has no option for the blob response type. I handled the case for myself. Do you think that is it worth to make a pr request?

**Comment by perry-mitchell** [comment]
I don’t provide a transpiled copy for the browser, but it’s something I’ve been considering. Would you mind sharing some code here so we can decide? Thanks :)

**Comment by perry-mitchell** [comment]
Working on releasing a browser-based version now.. with v3. Might be a good time to look into this :D

**Comment by perry-mitchell** [comment]
So right now I'm supporting `ArrayBuffer` for data transfer as it's just nicer to work with. Blobs aren't great. You can use the following to handle the conversion, most likely:

```javascript
client.getFileContents("/file.jpg").then(arrayBuffer => {
    const blob = new Blob([new Uint8Array(arrayBuffer)]);
});
```
