### ISSUE TITLE
Cancelable requests

### ISSUE THREAD

**Issue by skjnldsv** [perry-mitchell/webdav-client#179]
Passing a proper cancelToken to a `getDirectoryContents` options does not work.
If I just replace the `getDirectoryContents` function by a simple axios.get function, it works.

So I'm assuming there is something here that block the passing of the data to the final axios library?

``` js
import axios from 'axios'

/**
 * Creates a cancelable axios 'request object'.
 *
 * @param {function} request the axios promise request
 * @returns {Object}
 */
const CancelableRequest = function(request) {
	/**
	 * Generate an axios cancel token
	 */
	const CancelToken = axios.CancelToken
	const source = CancelToken.source()

	/**
	 * Execute the request
	 *
	 * @param {string} url the url to send the request to
	 * @param {Object} [options] optional config for the request
	 */
	const fetch = async function(url, options) {
		return request(
			url,
			Object.assign({ cancelToken: source.token }, { options })
		)
	}
	return {
		request: fetch,
		cancel: source.cancel
	}
}

export default CancelableRequest
```

``` js
const { request, cancel } = cancelableRequest(webdav.getDirectoryContents)
// enable slow network to have the time to cancel the request or add some delay to your webdav backend
request()
setTimeout(() => {
	cancel('Stop!')
}, 100)
```

**Comment by perry-mitchell** [comment]
Hmm, interesting. I like the idea of cancelable requests, but I'm not particularly onboard with cancelable promises. Your proposal makes sense but if this were to go through I'd prefer something simpler as I feel what axios has implemented is too cumbersome to be developer-friendly.

So in contradiction to my feelings on cancelable promises, perhaps something like the following would be suitable:

```javascript
const prom = webdav.getDirectoryContents("/");

// some time passes

prom.cancel();

// prom is rejected with a `RequestCancelledError`
```

The problem here is that due to async being awesome, the actual outcome of this is not defined. If cancel is called too late, the result might still be a resolved promise.

I feel like this could quickly become a conversation about cancellable promises - but I guess that's inevitable now.

**Comment by skjnldsv** [comment]
> I feel what axios has implemented is too cumbersome to be developer-friendly.

I would actually prefer if you do not change the way it is implemented. It would just make your maintenance of this library more complex. Axios is your main default xhr provider, let's use all of its functions fully. Any kind of shortcuts would probably generate future issues to fix after some axios updates.

**Comment by perry-mitchell** [comment]
I disagree - as mentioned in the PR the API of the client should not be dependent on the engine’s API. If I provide access to axios directly then I’m locked in to using axios, which I plan to replace. The cancel token that axios implemented is ugly and could be much simpler being that it’s just a function essentially that stops the request.

**Comment by skjnldsv** [comment]
Ah, yeah, I also disagree :smile_cat: 
Maintaining quite a lot of popular things is quite a weight.
This is open source, there are tons of incredible features/libraries that already exists. I feel like reinventing the wheel for the sake of independence is just a loss of time for a minimal gain.

Your library is a dav wrapper, why bothering implementing something as trivial as a request manager. Axios is one of the most used and devs are used to it, having to learn different standards across libraries also increase the barrier level entry for anyone trying to work with your library :confused: 

This is just my 2 cents. But in real life when a company does something fitting perfectly your need, you don't built your parts yourself, you pay them for their expertise and sustainability :wink:

**Comment by perry-mitchell** [comment]
Well I think this is a bit dramatic for what I’m proposing, which is a simple function to control a single feature. I’m not discussing a request manager - this is just a feature of the dav wrapper to cancel a request - how this is done is irrelevant in my opinion.

That being said, axios is also not maintained to an acceptable standard and I would not use it again in another project.

Agree to disagree - if my proposal is not for you then I’ll most likely pick it up myself 🙂

**Comment by perry-mitchell** [comment]
I appreciate the feedback and suggestion, and definitely see this as being a useful feature!

**Comment by skjnldsv** [comment]
> That being said, axios is also not maintained to an acceptable standard and I would not use it again in another project.

I'm interested in this. I use it in a lot of places. Any reading to give me? :)

Thanks for taking the time for me :)
If you go for something like 

> ```js
> const prom = webdav.getDirectoryContents("/");
> // some time passes
> 
> prom.cancel();
> // prom is rejected with a `RequestCancelledError`
> ```

Keep in mind I could use await with try/catch
So I could not access a request already fired to cancel it if I'm awaiting the promise :)


```js
const prom = await webdav.getDirectoryContents("/");
prom.cancel(); // too late, the request is finished
```

**Comment by perry-mitchell** [comment]
Hi @skjnldsv - Your point about try/catch is a good one, it does indeed make having the `cancel` method attached to the promise a difficult issue to solve. Ultimately it could be handled in other ways:

```javascript
const { promise, cancel } = webdav.getDirectoryContents("/");
```

But this too looks a bit ugly.

Ultimately I can't think of a better approach, for now, than the cancellation token idea. I've done a little reading and have seen quite a bit of conjecture on it, but it still seems very fragmented in terms of finding a standard approach. I'd want something that is more **generally accepted** or on its way to a **standards track**.

I know I might be asking too much here, but I honestly think that axios' method of using cancellation tokens is [cumbersome and overcomplicated](https://github.com/axios/axios#cancellation). It'd be better if we could do something like the following:

```javascript
const { createCancelToken, createClient } = require("webdav");

const client = createClient("https://test.com");
const cancelToken = createCancelToken();

client.getDirectoryContents("/", { cancelToken });

// later
cancelToken.cancel();
```

This would obscure the axios cancel token (which could still be returned), meaning that I can keep it from becoming a first-party API member. Thoughts?

> Thanks for taking the time for me

Ofcourse :)

**Comment by skjnldsv** [comment]
> Hi @skjnldsv - Your point about try/catch is a good one, it does indeed make having the `cancel` method attached to the promise a difficult issue to solve. Ultimately it could be handled in other ways:

Yes, this is the reason why axios have this token thing I think :)
I was confused as well at first, but in the end, I understood the rules that were blocking any kind of other solutions :/

I think your idea is nice!
It's basically similar to what axios do, but slightly nicer. :+1:

**Comment by perry-mitchell** [comment]
Well, we have an agreement! 😁

I'll see if I find time to add this soon, but if anyone else wants to implement it feel free. Please follow my example as a guide, if you do.

**Comment by skjnldsv** [comment]
Any news on this btw? :see_no_evil:

**Comment by perry-mitchell** [comment]
@skjnldsv Unfortunately no, sorry. I don't personallly have a lot of use for cancellable requests with WebDAV, though I'm still in favour of adding this feature. I'd like to think I'll get around to it - thanks for the reminder, by the way - but can't guarantee it. Let's see if this weekend is kinder time-wise :sweat_smile:

**Comment by perry-mitchell** [comment]
Not sure why this is still open, as `signal` support was added in v4 ([4.8.0](https://github.com/perry-mitchell/webdav-client/blob/master/CHANGELOG.md#v480)). It will obviously remain in v5 as well.
