### ISSUE TITLE
Unable to resolve module `stream` 

### ISSUE THREAD

**Issue by davidfang** [perry-mitchell/webdav-client#184]
error: bundling failed: Error: Unable to resolve module `stream` from `node_modules/webdav/dist/interface/createStream.js`: stream could not be found within the project.

in react native project

**Comment by Soknath** [comment]
I used to face the s same problem, this is because "stream" is a native node library which is not available in react-native. Finally, my temporary solution is modified it to use [stream-browserify](https://www.npmjs.com/package/stream-browserify). 

Hope this help.

**Comment by perry-mitchell** [comment]
Yes, under the `react-native` in `package.json` section you could place:

```
{
  "react-native": {
    "stream": "stream-browserify"
  }
}
```

**Comment by tchaumeny** [comment]
@perry-mitchell what section is that ? would you have an example ?
