### ISSUE TITLE
Typescript autocomplete VS Code

### ISSUE THREAD

**Issue by Stehos** [perry-mitchell/webdav-client#193]
Hi All,
I want to ask about import createClient into a typescript file.

I am using VS Code 1.41.1, Date 2019-12, Electron 6.1.5, Node.js 12.4.0 and if I try to require webdav as it is written in documentation, meaning: const { createClient } = require("webdav"); everything work fine but autocomplete of functions not.

I also tried import * as createClient from 'webdav'; but nothing seems to be working.
Only createClient.**createClient()** has autocomplete.

![obrázok](https://user-images.githubusercontent.com/14280770/73161257-67221300-40eb-11ea-8d52-38005a098f68.png)

Thank you.

**Comment by perry-mitchell** [comment]
@Stehos There are no types provided, yet, so it won't matter how you import. I will be changing this library to typescript at some stage, so once that's done you'll get type completion.
