### ISSUE TITLE
When using `deep` returns error 500

### ISSUE THREAD

**Issue by janswist** [perry-mitchell/webdav-client#199]
I have problem with `deep` property. 

`await client.getDirectoryContents(url, { deep: false, glob: "/**/*3604"})`

When I use `false` then it finds directory I need (I want to find folders that end with specific number), but when I use `deep: true` then I get this error:

```
{
    "message": "Request failed with status code 500",
    "name": "Error",
    "stack": "Error: Request failed with status code 500\n    at createError (/my_project/functions/node_modules/webdav/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/my_project/functions/node_modules/webdav/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/my_project/functions/node_modules/webdav/node_modules/axios/lib/adapters/http.js:236:11)\n    at IncomingMessage.emit (events.js:194:15)\n    at endReadableNT (_stream_readable.js:1103:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)",
    "config": {
        "url": "urlToWebdavServer",
        "method": "propfind",
        "headers": {
            "Accept": "text/plain",
            "Depth": "infinity",
            "Authorization": "Basic <hidden>",
            "User-Agent": "axios/0.19.2"
        },
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "responseType": "text",
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1
    }
}
```

**Comment by perry-mitchell** [comment]
I ran the following test against Yandex webdav without error:

```javascript
const client = createClient("https://webdav.yandex.com", {
    username: "-",
    password: "-"
});
client
    .getDirectoryContents("/", { deep: true, glob: "/**/*112*" })
    .then(contents => {
        console.log(contents);
    });
```

My file `/test112.bcup` is returned as expected. Perhaps this is a lack of support for deep requests on your webdav server? What type of server is it?

If you have any other services that support webdav please try the same on those.

**Comment by janswist** [comment]
I forgot to mention - it's ownCloud. Does it support that functionality?

**Comment by perry-mitchell** [comment]
@janswist Yes, I just ran the following against my personal ownCloud:

```javascript
client
    .getDirectoryContents("/", { deep: true, glob: "/**/*95716*" })
    .then(contents => {
        console.log(contents);
    });
```

It worked fine and returned what I expected.

Looking closer at your response, the `"Depth": "infinity"` header makes it seem like it's being made correctly. I'd recommend checking your owncloud server logs to see what's happening - there'll be something there that'll help.

Might help to also check what version of OC you're using, in case there's a regression issue.

**Comment by janswist** [comment]
I use `ownCloud 9.0.1 (stable)`. Would be grateful for checking if there's regression issue. There are to many files to download the whole list of them.

**Comment by perry-mitchell** [comment]
Well stable version is 10, not 9... I don't have access to 9 to test this, and I'd probably not put too much effort into supporting an older OC version anyhow, I'm afraid.

I think you should check your server logs as a next step - the errors there will be very telling in terms of what's going wrong. We can move forward after we know what's happening :)

**Comment by janswist** [comment]
It took a while, but I got information that on the server there is only access log. No stack trace.

Also, backend guy told me that glob is doing it's job [client side](https://github.com/perry-mitchell/webdav-client/blob/4719cfd363beddd7639462b9f04699a063c56ed3/source/interface/directoryContents.js#L29) so it should work regardless. Could you shed some more light on it, please?

**Comment by perry-mitchell** [comment]
Sorry @janswist - Without more information there's little I can do to help. As this library is currently working with many major webdav services, I suspect that the issue _may_ still be with your server's configuration. If this is not the case and you find a more concrete error or stacktrace, I'll happily look into patching it. I the mean time I'll close this as there's nothing to do.
