### ISSUE TITLE
Using proxy to connect to webdav server

### ISSUE THREAD

**Issue by Lamachael** [perry-mitchell/webdav-client#223]
Hi, this lib looks like the perfect solution to my problem, however, I need to setup a proxy option to connect to a webdav server, is there any workaround for this that I haven't found yet, or is it possible to include this feature?

Thanks, Tamas.

**Comment by perry-mitchell** [comment]
Hi @Lamachael - To be honest I have no idea how this would work via a proxy, but I'm happy to mark this as an issue that needs investigation. I don't think it shouldn't need any special configuration, as it's the responsibility of the proxy to forward requests, intact, to the webdav service.

**Comment by Lamachael** [comment]
Thanks @perry-mitchell, you are right, if the proxy is set on the environment variables properly on the computer axios shall handle that, but if I only need a specific proxy to connect to the webdav server only than that needs to be set. I've found a workaround in the meantime, I'll just put it here maybe somebody else make use of it also. It's uses the tunnel package to create a httpsAgent that uses proxy.

`const tunnel = require("./node_modules/tunnel") //this is the path to your node modules, maybe different for you
const agent = tunnel.httpsOverHttp ({
    proxy: {
        host: 'name-of-your-proxy',
        port: 8000 //use the port that is required for your proxy
    }
})

const client = createClient("webdav-server", { username: 'username', password: 'password',  httpsAgent: agent});
`

**Comment by perry-mitchell** [comment]
@Lamachael This looks quite nice, and I think it'd be acceptable to use this as a guide for others trying to connect via a proxy. I don't think additional support beyond custom agents is necessary, but I'm happy to discuss an alternative if something better is possible.

**Comment by perry-mitchell** [comment]
Closing this - if there's a way to implement this correctly I'd be interested in discussing it, but imo this is the responsibility of the connecting _agent_, which is already configurable.
