### ISSUE TITLE
Using correct username and password results in 401 Unauthorized

### ISSUE THREAD

**Issue by Freir96** [perry-mitchell/webdav-client#224]
I have a webdav-server set up locally, and I tested it with Windows file explorer, but using the same username and password in the code from example:
`const { createClient } = require('webdav');

async function dav() {
    const client = createClient(
        // '/webdav/',
        'http://localhost:2000',
        {
            username: 'username',
            password: 'password'
        }
    );
    //let res = await client.exists("/")
    //console.log('bip', res);
    // Get directory contents
    const directoryItems = await client.getDirectoryContents('/');
    console.log(directoryItems);
}
try {
    dav()
}
catch (e) {
    console.log('err', e)
}`

it shows 'Error: Request failed with status code 401'.
After using the same code in browser (Angular) it asks me about the username and password despite putting them in the "createClient".

**Comment by perry-mitchell** [comment]
@tipleyg Your issue is for a different repository - webdav-fs. This is webdav. Could you open the issue there?

**Comment by perry-mitchell** [comment]
Closing as this issue doesn't seem immediately relevant. Will reopen if it is.
