### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by NexusNull** [perry-mitchell/webdav-client#229]
Any plans on switching to typescript or give typescript support via DefinitelyTyped/DefinitelyTyped?

**Comment by perry-mitchell** [comment]
@NexusNull Yes! In fact I'm almost ready to release the typescript version (v4) in the coming days.

**Comment by perry-mitchell** [comment]
Typescript pre-release support available in [v4.0.0-r01](https://www.npmjs.com/package/webdav/v/4.0.0-r01)
