### ISSUE TITLE
404 error for .iso type file only for some shares

### ISSUE THREAD

**Issue by ramandraju** [perry-mitchell/webdav-client#23]
iam getting file not found error while fetching file contents of iso file... file was listed in directory contents but while iam trying to fetch iso file contents it was showing 404 - File or directory not found.

**Comment by perry-mitchell** [comment]
Hi @ramandraju - Could you please paste the code you're using? Perhaps even a console log of the exact path to the file that you're requesting would be helpful also (you can obscure any domains etc. that are private).

**Comment by perry-mitchell** [comment]
Closed due to inactivity. We can re-open if you're still getting the error.
