### ISSUE TITLE
How to getDirectoryContents with custom headers？

### ISSUE THREAD

**Issue by hr0109** [perry-mitchell/webdav-client#230]
I have try to add "headers" to options delivered to getDirectoryContents，but custom headers did not show on the actual request. So what should i do to achieve that goal?

**Comment by perry-mitchell** [comment]
Are you making the request from the browser or from Node? In the browser you need to consider CORS, and that you need to have CORS-approved headers before you can make a request with custom headers.

Also, how are you making the request? Can you include some code? The standard [`getDirectoryContents`](https://github.com/perry-mitchell/webdav-client/blob/master/source/factory.js#L261) doesn't provide a way to specify custom headers. Instead you would need to do a completely [custom request](https://github.com/perry-mitchell/webdav-client#custom-requests) to specify your own headers.

**Comment by perry-mitchell** [comment]
In v4 of the library you'll be able to include headers for all requests when using `createClient`. It may be possible to add custom headers per method in the future.
