### ISSUE TITLE
Accessing local files — Why use webdav-client when I can simply use Node.js Streams or Node's fs module?

### ISSUE THREAD

**Issue by horak** [perry-mitchell/webdav-client#236]
**What am I trying to do?** 
I am currently self-hosting a Nextcloud instance and would like to serve its files via a simple RESTful Node.js service running on the same server.

**Details**
Since both my Nextcloud instance and my node server are running on the same hardware, is there any advantage to using webdav-client or webdav-fs over simple using the Node.js fs module or Streams?

I'm new to webdav and self-hosting things so pardon the ignorance.

**Comment by perry-mitchell** [comment]
Hi @horak - Sorry for the delay in responding.

Good question - imo the answer is simple: Use this client and avoid building an extra Nodejs service to serve files. Nextcloud comes with WebDAV built in, and this client will allow you to interact with files and directories on your server without having to build anything extra server side. Nextcloud manages the file handling, permissions, quotas, **versioning**, **authentication** and loads more that you might simply overlook when building your own solution. Nextcloud is also maintained by a community, whereas presumably your server is just maintained by you. No matter who you are, this usually isn't a good trade off if you're not after some very specific functionality.

I hope this helps!

**Comment by horak** [comment]
Thanks @perry-mitchell! Very helpful response!
