### ISSUE TITLE
Allow specifying path for quota query

### ISSUE THREAD

**Issue by PVince81** [perry-mitchell/webdav-client#237]
In some environments like Nextcloud, the quota might not be the same depending on the path. This is because a user could have external storages mounted or received shares in which the quota of the owner would apply.

**Comment by PVince81** [comment]
At first I thought I can just do a stat and query the quota properties directly, but it's not possible to query custom props: https://github.com/perry-mitchell/webdav-client/issues/238

So will need to resort to "customRequest" and build the XML query on my own, not so nice.

**Comment by perry-mitchell** [comment]
Thanks @PVince81 - Do you know if quota is available on Nextcloud _per route_? Would be nice to have some sample output so I can turn this into a feature - in case anyone might contribute a snippet of XML.
