### ISSUE TITLE
Allow querying custom properties

### ISSUE THREAD

**Issue by PVince81** [perry-mitchell/webdav-client#238]
Nextcloud for example has additional properties (like checksum, tags, comments, etc) that can be queried with PROPFIND optionally and are not part of the default response.

The methods `stat` and `getDirectoryContents` should allow modifying the properties list to be queried.

Requires namespace support: https://github.com/perry-mitchell/webdav-client/issues/210

This will likely have an impact on the current parsing and would need a decision about how to return namespaces (ex: using clark notation).

**Comment by perry-mitchell** [comment]
I like this idea. I would happily entertain contributions regarding both the namespace support and custom properties.

I haven't yet seen a great example of where namespacing is useful or even present (multiple namespaces).

**Comment by skjnldsv** [comment]
Hey, it used to be possible on 3.x.x https://github.com/nextcloud/viewer/blob/0208dd519d0f266b309d765a73c0221a9d2dd8ee/src/services/FileInfo.js#L33-L61

But with latest 4.x.x it doesn't work anymore @perry-mitchell. Any insights?

**Comment by skjnldsv** [comment]
Ah, it's becaused you removed the data parametter in https://github.com/perry-mitchell/webdav-client/blob/68803823ef250451d11a33a3792bf928b37c4365/source/request.js#L62-L64

https://github.com/perry-mitchell/webdav-client/blob/edee122640a2f0cc8b47d176c868ac380c9592df/source/request.ts#L19

**Comment by perry-mitchell** [comment]
@skjnldsv I wasn't aware anyone was using the library like that - else I would have avoided such a change. That is kind of why the customRequest method exists at all. In the linked example you're passing a crazy amount of custom data to the stat call - If these were common use-cases I'm surprised someone hasn't contributed them to this library as a core method or feature.

I'll reintroduce this functionality now.

**Comment by perry-mitchell** [comment]
@skjnldsv Sorry for the inconvenience.. I'll document this better now so it won't mysteriously disappear again. 

I've added it back in v4.2.1. You can see it documented in the [method options](https://github.com/perry-mitchell/webdav-client#method-options) in the readme. It's available under the `data` property in the options argument for `stat` (and other methods).

**Comment by skjnldsv** [comment]
> I'm surprised someone hasn't contributed them to this library as a core method or feature

I'm very sorry, I did a few issues and prs here, but I'm also quite overwhelmed, I would love to spend a fair amount of time trying to push a bit more here :)
I'm sure we'll get a future work that will require a very extensive usage of thiw lib and we'll be able to contribute a bit more! :rocket:

**Comment by skjnldsv** [comment]
> Sorry for the inconvenience

No worries! It's all good, things happens :wink:
