### ISSUE TITLE
How get the file's share link ?

### ISSUE THREAD

**Issue by Silbad** [perry-mitchell/webdav-client#239]
Hello, 
I don't find how get the file's share link ? (I use Next-Cloud).
Is an option in getDirectoryContents method to get that ?
Thanks

**Comment by Silbad** [comment]
Ok I find a solution with getFileContents 
```
const fileContents = await client.getFileContents("/pathfile/image.jpg", {
            format: 'binary'
        });
const fileURL = URL.createObjectURL(new Blob([fileContents]));
```
If you have a better solution... ;)

**Comment by perry-mitchell** [comment]
You can use [`getFileDownloadLink`](https://github.com/perry-mitchell/webdav-client#getfiledownloadlink), but this **exposes authentication credentials in the URL**, and may not work for all WebDAV hosts.

The function to get a share link from a service like Nextcloud is usually bound up in their API and not necessarily possible to handle using WebDAV (therefore this library).

I hope this clears things up!

**Comment by Silbad** [comment]
Ok thanks, I'll keep my solution for now ;)
