### ISSUE TITLE
maxBodyLength at putFileContents not working

### ISSUE THREAD

**Issue by simatec** [perry-mitchell/webdav-client#240]
I upgraded my system from version 3.6.2 to 4.0.0.
With version `maxBodyLength` no longer works.
I get the following error

'Error [ERR_FR_MAX_BODY_LENGTH_EXCEEDED]: Request body larger than maxBodyLength limit'

Here is my Code:
```
await client.putFileContents(webdavFilename, fileContent, {
                    format: "binary", "Content-Type": "application/octet-stream", 'maxBodyLength': Infinity, onUploadProgress: progress => {
                        log.debug(`Uploaded ${progress.loaded} bytes of ${progress.total}`);
                    }
                })
```

Do I have to change anything in version 4.0.0 or is this a bug?
Version 3.6.2 runs without errors

**Comment by perry-mitchell** [comment]
@simatec `maxBodyLength` has to be specified at [client creation](https://github.com/perry-mitchell/webdav-client#client-configuration), not in the `putFileContents` method options.
