### ISSUE TITLE
Changeable authorization header

### ISSUE THREAD

**Issue by NexusNull** [perry-mitchell/webdav-client#241]
I'm working with a back-end that uses 'json web tokens', these are short lived, generally 2 hours, but a user can stay in one session for a lot longer, so I need a way to modify the Authorization header when it reached it's end of life.

**Comment by perry-mitchell** [comment]
Good point! I was meant to add an issue to allow for such functionality, but I've just added it now: #242

Once headers can be overridden you can provide your own `Authorization` header..

**Comment by perry-mitchell** [comment]
Closing this in favour of #242 - we can track the progress there.
