### ISSUE TITLE
Headers override for each request

### ISSUE THREAD

**Issue by perry-mitchell** [perry-mitchell/webdav-client#242]
Provide an option for all requests to override all headers in a request.

Currently the `headers` option on client creation is overridden by method-specific headers. Providing a `headers` option for each client method will allow overriding all other headers for specific requests.

**Comment by NexusNull** [comment]
I need to feature to continue on my project so I'd like to pitch in. Could you assign this feature to me?

**Comment by NexusNull** [comment]
This [NexusNull:master](https://github.com/perry-mitchell/webdav-client/compare/master...NexusNull:master) what I need. I'm working on implementing function specific headers.

**Comment by perry-mitchell** [comment]
@NexusNull I took a look at your proposal, but it's not how I'd see it implemented, unfortunately. Take for instance [`GetFileContentsOptions`](https://github.com/perry-mitchell/webdav-client/blob/master/source/types.ts#L105).. I would see that it's changed to extend a _base_ options type:

```typescript
interface WebDAVRequestOptions {
    headers?: Headers;
}

export interface GetFileContentsOptions extends WebDAVRequestOptions {
    details?: boolean;
    format?: "binary" | "text";
}
```

This way, when making any such request, you could pass options to that method specifying the override headers:

```typescript
await client.getFileContents("/test/my-file.dat", {
    headers: {
        "X-my-header": "abc123"
    }
});
```

This way, we have 2 methods of specifying the headers:

 * When calling `createClient` (base headers, overridden later)
 * When calling _any_ method (specific, overriding headers)

**Comment by perry-mitchell** [comment]
I'll have time later today to implement this, most likely.

**Comment by perry-mitchell** [comment]
@NexusNull Looking at your work a second time, I still see the use in it. It _won't_ work for the auth header, but it would still be generally useful for changing headers later on. I'd accept a PR if:

 * The methods were `setHeaders` and `getHeaders` (not `getHeader`)
 * The `setHeaders` completely rewrote the object, _not_ merged it

**Comment by NexusNull** [comment]
Why wouldn't it work for the auth header?

**Comment by perry-mitchell** [comment]
> Why wouldn't it work for the auth header?

Because the headers in the WebDAV context are overridden by the headers used by the specific method, such as authorisation. The override flow is as follows:

1. Context headers (that you're setting)
2. Method internal headers (not modifiable)
3. _New_: `headers` option per method

_1 is applied first, 3 last._

**Comment by perry-mitchell** [comment]
@NexusNull Please see the new functionality introduced in #244 for overriding the `Authorization` header.
