### ISSUE TITLE
Importing types causes errors when building with typescript

### ISSUE THREAD

**Issue by NexusNull** [perry-mitchell/webdav-client#248]
First of all let me mention that I don't have much experience with typescript so I'm unsure if the issue is really with this library or if I'm doing something wrong.

Alright I'm using 
webdav-client@4.2.1 
typescript@3.0.3 
node: v14.16.0

when trying to import `WebDAVClientError` with 

```
// @ts-ignore
import {WebDAVClientError} from "webdav";

const webdav = require("webdav");  // might be relevant, I dunno
```
The typescript compiler screams these two errors at me

```
node_modules/webdav/dist/node/compat/patcher.d.ts:1:24 - error TS7016: Could not find a declaration file for module 'hot-patcher'. '/home/nexus/Development/WebstormProjects/BrowserFS/node_modules/hot-patcher/source/index.js' implicitly has an 'any' type.
  Try `npm install @types/hot-patcher` if it exists or add a new declaration (.d.ts) file containing `declare module 'hot-patcher';`

1 import HotPatcher from "hot-patcher";
                         ~~~~~~~~~~~~~
```

```
node_modules/webdav/dist/node/types.d.ts:2:8 - error TS1192: Module '"stream"' has no default export.

2 import Stream from "stream";
         ~~~~~~
```

I already found a fix for this but it involves editing the files in question and putting a @ts-ignore on top of them, I doubt that's a proper fix tough. Another fix that I could think of is just copying the definition over, but that doesn't feel right either.
For now I'll probably just copy the def over, but if you happen to know a simple way to fix that in this repo that would be amazing.

**Comment by perry-mitchell** [comment]
Hi @NexusNull - I have a feeling that your TS config might be on the strict-side.. As you can see from the tests, WebDAV builds just fine without HotPatcher having any types. Perhaps adjusting your build rules will allow this? HotPatcher is used mostly internally and unless you're interacting with it for some strange reason, it's not necessary to even know about it.

**Comment by NexusNull** [comment]
I have since dropped the entire library that had the issue, the original maintainer left and silly me thought I had to use it so I spend considerable amount of time getting it to work for my use case, well you live and learn. 

Also thanks for keeping this maintained like you do.

**Comment by javilag** [comment]
i'm trying to make a build with webdav but i'm finding the next error ```
"node_modules/webdav/dist/node/compat/patcher.d.ts:1:24 - error TS7016: Could not find a declaration file for module 'hot-patcher'. '.../node_modules/webdav/node_modules/hot-patcher/source/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/hot-patcher` if it exists or add a new declaration (.d.ts) file containing `declare module 'hot-patcher';`

1 import HotPatcher from "hot-patcher";
```
i'm using the strict mode in false and this error still happen.
