### ISSUE TITLE
putFileContents does not pass onUploadProgress to axios

### ISSUE THREAD

**Issue by tmpfs** [perry-mitchell/webdav-client#249]
Just spent a lot of time debugging why my progress handler was not firing and finally figured out that `putFileContents` is not passing `onUploadProgress` to axios.

I am not sure what the correct fix for this is but happy to submit a *quick* fix (directly assign to `requestOptions`) it you would take the PR.

My guess is the bug is in `prepareRequestOptions()`.

**Comment by NKnuelle** [comment]
Looks good to me. I would need this fix, too so I hope the commit is approved 👍

**Comment by NKnuelle** [comment]
Hi,
is there any update on this topic? Can we do something to help?

Greetings!

**Comment by perry-mitchell** [comment]
@NKnuelle This PR was left in the middle of a review and I haven't had time to look into it myself: https://github.com/perry-mitchell/webdav-client/pull/250

It could be tidied up or re-made and that'd help, of course.. I will eventually get time to do that myself but I'd appreciate someone else doing that as well of course 🙏

**Comment by n-peugnet** [comment]
@perry-mitchell I just rebased and cleaned #250 to only keep essential changes in this new pull request: https://github.com/perry-mitchell/webdav-client/pull/263
