### ISSUE TITLE
Problems using this library with Nuxt.js

### ISSUE THREAD

**Issue by NKnuelle** [perry-mitchell/webdav-client#252]
Hello,

I am trying to use this library in my Vue/Nuxt-Project but I keep getting these errors:

1. `Can't resolve 'fs'` when building the project.
2. ```ERROR  Failed to compile with 1 errors This dependency was not found: * fs in ./store/webdav.js To install it, you can run: npm install --save fs``` when running in development mode

My webdav.js looks like this:
```
export const state = () => ({
  client: null
})

export const mutations = {
  setClient (state, client) {
    this.client = client
  }
}
export const actions = {
  login ({ commit }, { username, password }) {
    return new Promise((resolve, reject) => {
      const { createClient } = require('webdav')
      const client = createClient(
        'http://localhost',
        {
          username,
          password
        }
      )
      client.stat('/').then((response) => {
        commit('setClient', client)
        resolve(response)
      }, (error) => {
        reject(error)
      })
    })
  },
  upload ({ commit }, { localFilePath, remoteFilePath }) {
    return new Promise((resolve, reject) => {
      const fs = require('fs');
      fs.createReadStream(localFilePath)
      state.client.createWriteStream(remoteFilePath)
    })
  }
}

```

The problem is with the `upload`method where the build-in node.js fs module is used. I searched a lot of time to resolve this issue but I can't find a solution. The problem seems to be that the fs module is s server-side module - my Nuxt project is defined as a server-side project (which is the default for Nuxt: https://nuxtjs.org/docs/2.x/get-started/commands). This is also shown when running the dev server so the fs module should be available?
<img width="380" alt="nodejs_bug" src="https://user-images.githubusercontent.com/24235417/112624741-490a8c80-8e2e-11eb-93e0-83b767129080.PNG">

I am very confused how to use this library as I am trying to build a Web App so that users can upload/download their local files to a remote WebDAV server. This should be possible with this library as far as I understand, right?

Any help very appreciated!

**Comment by perry-mitchell** [comment]
Hi @NKnuelle - this is most likely a configuration issue on the Nuxt side - WebDAV doesn't reference "fs" anywhere.

You can try importing WebDAV from the web route, in case it expects a web target: `import { createClient } from "webdav/web";`. But I suspect the "fs" error is coming from somewhere else.

I hope you find the issue. If you discover some other issue that is addressable via this project, please let me know and we can find a solution.

**Comment by storageddd** [comment]
I found solution how it can use with nuxt 2:
1. Import must be from 'webdav/dist/web/index' (or configure aliases)
2. Import must be at client side (if u try to use it at server side u catch error).

So, next snippet from my usage:
```
 mounted() {
    this.initializeClient();
  },
  methods: {
    async initializeClient() {
      if (process.server) {
        return;
      }

      const { baseUrl, credentials } = this;
      if (!credentials.username || !credentials.password) {
        throw new Error('Сredentials missed');
      }

      const webdav = await import('webdav/dist/web/index');
      const { createClient } = webdav;
      this.client = createClient(baseUrl, credentials);
    }
}
```
