### ISSUE TITLE
Cannot read response object from error when http status is 404

### ISSUE THREAD

**Issue by dpakach** [perry-mitchell/webdav-client#261]
When making a dav request, if we get 4xx status code, then we cannot read the response object from the error.

eg. 
```
const { createClient } = require("webdav");

const client = createClient(
    "http://<dav-server>",
    {
        username: "admin",
        password: "admin"
    }
);

// Get directory contents for a folder that doesn't exists
const directoryItems = client.getDirectoryContents("/non-existing-file");

directoryItems.then(items => {
  console.log(items)
}).catch(err => {
  console.log(err.response.data)
}) 
```
In version 4.1.0 we can read the body of the actual response
```
node index.js
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>File with name non-existing-file could not be located</s:message>
</d:error>
```

but with the latest version 4.4.0, the response object is not returned in the error
```
 node index.js
(node:92563) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'data' of undefined
    at directoryItems.then.catch.err (/home/dipakacharya/Documents/playground/davtest/index.js:17:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:92563) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:92563) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. 
```

**Comment by qtarant** [comment]
Hello. I have the exact same problem. I am using the owncloud-sdk which depends on this package and it have the same problem. I have tested different releases (4.0 and above) but all of them have the same problem.

**Comment by perry-mitchell** [comment]
Thanks for the report, looking into this now.

**Comment by perry-mitchell** [comment]
I don't see that 4.1.0 would have had `response.data` on the errors being thrown from this library: https://github.com/perry-mitchell/webdav-client/compare/v4.1.0...v4.2.0

Can someone point me to the regression that occurred after 4.1.0?

Also, if you check the types, `error.response` is not a supported property, so I can't see how this would have worked in any 4.x version. I am happy adding such support, however.

**Comment by dpakach** [comment]
@perry-mitchell, found that the issue was because the error is not handled by axios for any status codes (https://github.com/perry-mitchell/webdav-client/blob/master/source/request.ts#L52). And the `handleResponseCode` only added status property.

I've made a simple fix PR that worked for me, please have a look https://github.com/perry-mitchell/webdav-client/pull/262
thanks

**Comment by qtarant** [comment]
I can confirm that the fix proposed for @dpakach in his last comment (#262) worked for me also, now I can get the error message in responses with status >= 400
Thanks a lot, @dpakach

**Comment by perry-mitchell** [comment]
Thanks @dpakach - I left a review on the MR. If we agree I'll happily merge it this week.

**Comment by dpakach** [comment]
@perry-mitchell, I've fixed the PR according to your review, please have a look
