### ISSUE TITLE
getFileContents returns an object even with format: 'text' specified for json files

### ISSUE THREAD

**Issue by mofojed** [perry-mitchell/webdav-client#267]
Steps to Reproduce:
1) Connect to a webdav client that has a simple JSON file, eg. simple-array.json: `["a", "b", "c"]`
2) Use the client to retrieve the contents as a string:
```
const content = await client.getFileContents('./simple-array.json', { format: 'text' });
console.log('Content type is', typeof content);
```
3) Check the console log

Expected Results:
3) `Content type is string` printed to the console

Actual Results:
3) `Content type is object` printed to the console. The returned contents are not a string.

**Comment by perry-mitchell** [comment]
Good catch! Just reproduced this. It is indeed a bug, and probably due to the underlying request library I'm using.

**Comment by perry-mitchell** [comment]
Issue was with axios being buggy as heck - axios/axios#811

I'll be removing axios in the next major version..

**Comment by perry-mitchell** [comment]
Publishing as 4.6.1

**Comment by mofojed** [comment]
Awesome, thanks for the quick response!
