### ISSUE TITLE
Replace axios with something simpler

### ISSUE THREAD

**Issue by perry-mitchell** [perry-mitchell/webdav-client#269]
Axios should be replaced. It's overpowered for what we need, and has a lot of bloat and quite a slow release cycle. [cowl](https://github.com/perry-mitchell/cowl) would be a better fit.

**Comment by baybal** [comment]
Nodejs now support browser fetch. I don't think we are using that much of Axios functionality.

**Comment by perry-mitchell** [comment]
Axios will be dropped in v5.
