### ISSUE TITLE
Rollup says createClient is not exported by the web client

### ISSUE THREAD

**Issue by TheBlueOompaLoompa** [perry-mitchell/webdav-client#279]
This is what rollup spits out:
```
Error: 'createClient' is not exported by node_modules/webdav/web/index.js, imported by src/webfs.ts
```
The only code I have so far is:
```typescript
import { createClient } from "webdav/web";
```

I'm using svelte with the typescript plugin and this code is in a typescript file. I'm using yarn as my package manager.

**Comment by perry-mitchell** [comment]
I'm sorry, but this is most likely an error with your build system. This library's web component is used [in other projects](https://github.com/buttercup/buttercup-core/blob/master/source/env/web/net.ts) successfully.
