### ISSUE TITLE
Image upload format problem with Webdav NextCloud 

### ISSUE THREAD

**Issue by m90khan** [perry-mitchell/webdav-client#281]
Hi, 
I am trying to upload image base64 to NextCloud using putFileContents. The image file gets uploaded but error on loading image. jpg extension did not get established. I am using React.

  const downloadResult = await fetch(base64Image);

      const fileName = 'file.jpg'
      await client.putFileContents(fileName, downloadResult.url, {
        overwrite: false,
        onUploadProgress: progress => {
          console.log(`Uploaded ${progress.loaded} bytes of ${progress.total}`);
        }
      });
      
![image](https://user-images.githubusercontent.com/6104751/145444874-5327ce3c-4ac3-46eb-b650-50b3f05d98dd.png)

**Comment by perry-mitchell** [comment]
You don’t put file names, but file paths. Try with a / at the start of the filename. 

I use this library against Nextcloud daily without issue :)
