### ISSUE TITLE
Need Help... Url changes after login can't access root directory

### ISSUE THREAD

**Issue by donbenci13** [perry-mitchell/webdav-client#287]
the url has a "/WebInterface/login.html" when login in to the server, but after login it goes back to it's base URL.

now the problem is, when I'm trying to access the root directory. It tells me **'Not Found: Resource does not exist'** because the path value is with "/WebInterface/login.html".

**Comment by perry-mitchell** [comment]
Unfortunately this is not enough information for us to be able to help you. It's most likely the wrong URL you're pointing to, for the WebDAV API. Please consult the documentation for your provider, or ask support what the correct webdav configuration is.
