### ISSUE TITLE
`.exists` error on exists dir

### ISSUE THREAD

**Issue by loynoir** [perry-mitchell/webdav-client#289]
```js
> await client.exists('/foobar//')
true
> await client.exists('/foobar/')
true
> await client.exists('/foobar')
400 Bad Request
```

**Comment by loynoir** [comment]
Related

```js
await client.createDirectory(`/a/b/c/d`, { recursive: true })
400 Bad Request
await client.createDirectory(`/a/b/c/d`, { recursive: true })
400 Bad Request
```

**Comment by perry-mitchell** [comment]
>  await client.exists('/foobar')
> 400 Bad Request

https://github.com/perry-mitchell/webdav-client/blob/master/test/node/operations/exists.spec.js#L35-L39

> await client.createDirectory('/a/b/c/d', { recursive: true })
> 400 Bad Request

https://github.com/perry-mitchell/webdav-client/blob/master/test/node/operations/createDirectory.spec.js#L57-L62

@loynoir Unfortunately if the tests are checking this exact thing, and they're passing, there's nothing I can do with this information. If you're interested in helping address your issue in this repo please consider adding a PR with failing tests.

**Comment by perry-mitchell** [comment]
Alternatively perhaps there could be some relation to #290, but who knows.

**Comment by loynoir** [comment]
Tested on docker image [bytemark/webdav](https://hub.docker.com/r/bytemark/webdav), which is apache server with webdav config
