### ISSUE TITLE
Can operation multi-files once time

### ISSUE THREAD

**Issue by rowthan** [perry-mitchell/webdav-client#294]
Can I delete, update or get multi-files by a single HTTP request?
like this:
```
const files = ["a.text","b.text"];
client.getFilesContents(files).then(function(resultArray){
  console.log(resultArray) // ["content from a.text", "content from b.text"]
})
```

Because there is a request limited by webdav server, so I'd like request multi-files each time to avoid reach the limit.

**Comment by perry-mitchell** [comment]
There isn't yet, but this is a great idea for a new major release. Adding some kind of "transaction" API to allow for multi-request multi-response. Is there some kind of standard for this on WebDAV? I've not seen it at least.

**Comment by perry-mitchell** [comment]
Closing as stale.
