### ISSUE TITLE
Response the meta info of the file after  putFileContents

### ISSUE THREAD

**Issue by rowthan** [perry-mitchell/webdav-client#296]
Now, the return type of pushFileContents is boolean. can it be fileStat instead?

**Comment by perry-mitchell** [comment]
That would require an extra request to get the stats, as far as I'm aware. I'd prefer functions to make as little network traffic as necessary. Can't you just make a wrapper for that?

```typescript
async function putAndStat(path: string, contents: Buffer): Promise<FileStat> {
  await client.putFileContents(path, contents);
  return client.stat(path);
}

**Comment by perry-mitchell** [comment]
Will close as I think this was answered.

**Comment by rowthan** [comment]
That is what I do now, but I think it's a waste of network.
It may be better returned by the putFileContents method.
but I am not sure it's a problem of webdav protocol(webdav protocol did not response the file meta info) or webdav-client(lose or block the meta info)
