### ISSUE TITLE
To set up multiple client connection

### ISSUE THREAD

**Issue by ashilprakash** [perry-mitchell/webdav-client#298]
I have a Json file that contains multiple sync server details, My requirement is like, to set up connection dynamically and perform some methods in that particular sync server. I have provided my sample code snippet below, when I run this, I am not able to get proper client details, its showing error. Could u please help me to sort this out.

async function webd(Url, username, password) {

    client = createClient(
        Url,
        {
            username: username,
            password: password
        }
    )

    const directoryItems = await client.getDirectoryContents("/From Citus Health Integration Engine/Progress Notes/pdf")

    // console.log(directoryItems)

    directoryItems.forEach(items => {
        var des = items.filename.split('/')
        var dest = des[des.length - 1]
        // console.log(dest)

        console.log(items.filename)

        getContent(items.filename)

    })
    async function getContent(filename) {
        var a = await client.getFileContents(filename, { format: "text" })
        console.log(a)
    }
}

fs.readFile('client_details.json', (err, data) => {
    client_details = JSON.parse(data)
    details = client_details.SyncServerDetails;

    for (i = 0; i < details.length; i++) {

        webd(details[i].SyncServerInfo.Url, details[i].SyncServerInfo.username, details[i].SyncServerInfo.password)
    }

})

**Comment by perry-mitchell** [comment]
What error are you seeing?

For a start, your `getContent` function is asynchronous, and you're calling it from a `forEach` loop. This is incorrect.

Perhaps you want:

```javascript
for (const items of directoryItems) {
// ...
```

**Comment by perry-mitchell** [comment]
I'll close for now. If the issue persists and you add more information, I'll reopen.
