### ISSUE TITLE
putFileContents() not sent request

### ISSUE THREAD

**Issue by jyasuu** [perry-mitchell/webdav-client#299]
Using "webdav": "^4.8.0"

I've been trying to use this component to upload files recently, but found that it doesn't send out the request, and found some problems from the console, I suspect that I may be missing some packages installed causing stream_1.default.readable to be undefined .How can I fix it?

<img width="610" alt="image" src="https://user-images.githubusercontent.com/13827723/159201533-ae377e34-8014-41a6-aa29-368d2afe9c36.png">

**Comment by perry-mitchell** [comment]
You're using the wrong bundle. I provide a web bundle for use in browsers - please do not use the node version and transpile it yourself.

Please read the [instructions](https://github.com/perry-mitchell/webdav-client#browser-support).
