### ISSUE TITLE
Vulnerable url-parse version

### ISSUE THREAD

**Issue by pumano** [perry-mitchell/webdav-client#300]
Please update url-parse to latest non vulnerable version.

npm audit provides info:

url-parse  <=1.5.8
fixed in 1.5.9
**Severity: critical**
Authorization bypass in url-parse - https://github.com/advisories/GHSA-rqff-837h-mm52
Incorrect returned href via an '@' sign but no user info and hostname - https://github.com/advisories/GHSA-8v38-pw62-9cw2
Incorrect hostname / protocol due to unstripped leading control characters. - https://github.com/advisories/GHSA-jf5r-8hm2-f872
Authorization Bypass Through User-Controlled Key in url-parse - https://github.com/advisories/GHSA-hgjh-723h-mx2j
fix available via `npm audit fix`
node_modules/url-parse`

```
% npm ls url-parse
myproject@1.0.0
└─┬ webdav@4.8.0
  └── url-parse@1.5.3
```

**Comment by perry-mitchell** [comment]
Released in 4.9.0
