### ISSUE TITLE
Is it possible to append a new line to file on webdav server? 

### ISSUE THREAD

**Issue by towith** [perry-mitchell/webdav-client#303]
Hi , thanks for your cool tool first , Is it possible to append a new line to file on webdav server? 
for now , I have to fetch remote file first, then append new line, then overwrite the remote file again.
It's better if there's a `append line` on put method directly
Thanks

**Comment by perry-mitchell** [comment]
Thanks!

It seems like [SabreDAV supports this](https://sabre.io/dav/http-patch/), though I'm not sure about other WebDAV servers.

I'd accept a PR for this.

**Comment by towith** [comment]
OK, thanks your kind recommendation

**Comment by ArcticLampyrid** [comment]
Apache should this too, but in a different way.

https://github.com/miquels/webdav-handler-rs/blob/master/doc/Apache-PUT-with-Content-Range.md
