### ISSUE TITLE
Some wrong when I use putFileContents in react native

### ISSUE THREAD

**Issue by fenglang0203** [perry-mitchell/webdav-client#304]
When I use putFileContents in react native, I have this wrong message, how can I solve this?

TypeError: Right-hand side of 'instanceof' is not an object
    at putFileContents.js:63

**Comment by perry-mitchell** [comment]
Seems that you might be hitting [this line](https://github.com/perry-mitchell/webdav-client/blob/master/source/operations/putFileContents.ts#L31) and failing, due to `Stream` not being set.

**Comment by perry-mitchell** [comment]
Fixed in 4.10.0
