### ISSUE TITLE
TypeError: n is not a constructor when calling client.createReadStream()

### ISSUE THREAD

**Issue by mtdvlpr** [perry-mitchell/webdav-client#312]
I'm trying to use the streams to up and download files from a webdav server. I am calling client.createReadStream() with just a url, without any additional options. This gives the error in the title. It translates to the PassThrough variable I think.

**Comment by perry-mitchell** [comment]
Hi, are you using this in the browser or in Node? And are you using the correct import for that environment?

There are 2 separate builds and the web one is without stream support.

**Comment by mtdvlpr** [comment]
That explains it. I'm using the web one.
