### ISSUE TITLE
UTF-8 4-byte characters not working

### ISSUE THREAD

**Issue by RedDeffender** [perry-mitchell/webdav-client#321]
It seems like filenames with UTF-8 4-byte characters [(examples)](https://design215.com/toolbox/utf8-4byte-characters.php) do not work. I only tried uploading files. I don't get any error when uploading but the file never appears on the server. Filenames with UTF-8 3-byte characters work normally.

**Comment by perry-mitchell** [comment]
I'd happily accept a PR for this, or even a PR that adds failing tests, so I can fix them.

**Comment by susnux** [comment]
For me 4byte characters work as expected (emojis etc) using this library with both the test server (`webdav-server`) as well as with e.g. Nextcloud.

**Comment by perry-mitchell** [comment]
Closing as stale.
