### ISSUE TITLE
[BUG] getDirectoryContents for 4shared webdav server removes parent folder from location

### ISSUE THREAD

**Issue by mtdvlpr** [perry-mitchell/webdav-client#322]
When I connect to a 4shared webdav server, the getDirectoryContents method somehow removes the direct parent from the filename.
For example:
The file '/Media/09-29-2022/image.png' will get the filename property '/Media/image.png'
The directory '/Media/09-28-2022' will get the filename property '/09-28-2022'

I've seen a correct implementation [here](https://www.filestash.app/webdav-client.html), so it's probably not a bug with 4shared itself.

Could you please fix this? My userbase depends on this. If a fix is not imminent, could you provide a workaround in the meantime?

**Comment by perry-mitchell** [comment]
I could try to check later, but I don't have time right now sorry.

There are some things that would help speed this up however:
- Code for the working example app
- Copy+pasted response from your account when using getDirectoryContents

Make sure to obscure any sensitive information if you do. I'd also accept a PR addressing the issue if you find the problem.

**Comment by mtdvlpr** [comment]
Hi, nevermind. I digged a little deeper and it turns out, it is a bug in 4shared itself! Their xml response is broken.
