### ISSUE TITLE
Use OIDC to authenticate to keycloak instead of fix username and password

### ISSUE THREAD

**Issue by bitvilag** [perry-mitchell/webdav-client#328]
I currently use keycloak as user backend using the OIDC protocol and I am moving the nextcloud instance to this as well. I was wondering if you ever tried to interact with nextcloud using tokens creating a personal account/space for the user?

**Comment by perry-mitchell** [comment]
Hi @bitvilag - I moved this to the base repo, where such a feature would be implemented.

I'm not sure I understand what you're asking - Wouldn't such a setup still result in something like a [token](https://github.com/perry-mitchell/webdav-client#oauth-tokens)? This library isn't so much concerned about the authentication flow as it is about WebDAV interoperability.

Basically: could you kindly elaborate as to what you would expect this library to have implemented to support your way of working?

**Comment by bitvilag** [comment]
Dear @perry-mitchell,

I am still on the "figuring out" phase, but I also looked into a different library and asked the same question: https://github.com/tentwentyfour/nextcloud-link/issues/54

There, I elaborate a bit better on the use-case.

**Comment by perry-mitchell** [comment]
I'm going to close this for now. If this gets fleshed out a bit more I'll happily reopen. Thanks.
