### ISSUE TITLE
`putFileContents()` and `putTextContents()` functions are equal

### ISSUE THREAD

**Issue by piranna** [perry-mitchell/webdav-client#33]
Shouldn't one of them be removed?

**Comment by perry-mitchell** [comment]
Yes, seems the `putTextContents` should probably be removed; You can see [here](https://github.com/perry-mitchell/webdav-client/blob/master/source/clientFactory.js#L174) that they're switched on the format, but they don't seem to use that at all.

I think that [a header should be set](https://github.com/perry-mitchell/webdav-client/blob/master/source/adapter/put.js#L30) like `Content-Type: text/plain` for text, but other than that it could remain the same function.

**Comment by piranna** [comment]
> I think that a header should be set like Content-Type: text/plain for text, but other than that it could remain the same function.

I would not put a `Content-Type` header at all... we would need to see if the WebDAV spec talks something about any distinction for text files, but I doubt it.
