### ISSUE TITLE
Allow providing external HA1 for digest auth

### ISSUE THREAD

**Issue by manuelottlik** [perry-mitchell/webdav-client#332]
We have a use case where we want to use Digest Auth to make SSO possible for our users. Therefore we want to generate and save the HA1 on login and store it, so we don't have to store the password as described in [the advantages of the wikipedia entry about digest auth](https://en.wikipedia.org/wiki/Digest_access_authentication#Advantages).

We already implemented a solution for this in a fork and would be ready to contribute. It does not affect the existing workflow with username and password and essentially just adds an `ha1` attribute to all necessary functions.

**Comment by perry-mitchell** [comment]
Sounds interesting.. Would you have a link I could check out? Please also feel free to make a PR here so I can check it.. 

If it's a useful mechanism for digest auth that'd help others I'd happily consider adding it here. I don't personally have a need for it but I've seen that a decent number of people do use digest with this library.

**Comment by manuelottlik** [comment]
I just opened the PR. We are already using our fork in our product in the testing stage and it works like a charm. HA1 is generated on login, persisted in local storage and can therefore be used even after a reload of the page.

**Comment by manuelottlik** [comment]
@perry-mitchell do you have any update on this?

**Comment by perry-mitchell** [comment]
@manuelottlik Apologies for not checking sooner! I just reviewed it.. Had a few small items.

**Comment by manuelottlik** [comment]
Thank you for merging my PR, my first real open source contribution 🎉 

Do you already know when you publish a new RC of v5 so we can use it in our product?

**Comment by perry-mitchell** [comment]
Sorry @manuelottlik - It slipped my mind 😅. Released `5.0.0-r3` now.
