### ISSUE TITLE
409 error for upload

### ISSUE THREAD

**Issue by SINAKZM** [perry-mitchell/webdav-client#348]
hi . your library provide method for get upload link based on filename but how i can upload i get error 409 and this is my code
      const formData = new FormData();
      formData.append('file', this.selectedFile);  // Append selected file to the form data
      const config = {
        auth:{
          username:"admin",
          password:"admin",
        },
        headers: {
          'Content-Type': 'multipart/form-data'
        }
      };
      try {
        const response = await axios.put(
            "http://admin:admin@nextcloud_proxy_backend.develop/remote.php/dav/files/admin",
            formData,
            config
        );
        console.log('File uploaded successfully:', response);
      } catch (error) {
        console.error('Error uploading file:', error);
      }
can anyone give me help fo this?

**Comment by perry-mitchell** [comment]
Hi. Your code doesn't show how you use this library. Could you please update your example so that it does?

Also, 409 means conflict so the server is complaining due to some state most likely.
