### ISSUE TITLE
storage size

### ISSUE THREAD

**Issue by piranna** [perry-mitchell/webdav-client#35]
Add support for [storage size and quotas](https://tools.ietf.org/html/rfc4331).

**Comment by perry-mitchell** [comment]
@piranna You mean like reading the quota?

```xml
<D:quota-available-bytes>596650</D:quota-available-bytes>
<D:quota-used-bytes>403350</D:quota-used-bytes>
```

**Comment by piranna** [comment]
I'm mostly interested to know the size of the remote available space, but seems the correct way is to ask for the quota, yes.

**Comment by piranna** [comment]
Thank you! :-)
