### ISSUE TITLE
Can not be imported with newer node versions

### ISSUE THREAD

**Issue by susnux** [perry-mitchell/webdav-client#355]
The package can not be imported by some build tools and newer node versions, because the `exports` field of the package.json contain a folder mapping:

https://github.com/perry-mitchell/webdav-client/blob/630168b8183b2c89b71e38149ff502366ddee6d1/package.json#L11

This is deprecated since Node 14 and removed in Node 17. It should be replaced with:
```
"./dist/*": "./dist/*"
```

**Comment by skjnldsv** [comment]
Ref: https://github.com/perry-mitchell/webdav-client/issues/339
