### ISSUE TITLE
Is there a guide about how to use this lib in react-native?

### ISSUE THREAD

**Issue by maotoumao** [perry-mitchell/webdav-client#359]
I want to use this lib in my react-native app, but have no idea where to start.

---

I tried this:
```
import {createClient, AuthType} from 'webdav';

/// ...
const client = createClient('https://dav.jianguoyun.com/dav/', {
        authType: AuthType.Password,
        username: 'xxx',
        password: 'xxx',
 });
await client.getDirectoryContents('/');
```
and I got a ReferenceError: ```Property 'document' doesn't exist.``` (seems that the error was raised by **decodeHTMLEntities** function)

I also checked out [this respository](https://github.com/buttercup/buttercup-mobile) and tried to import the lib as if running in Node environment:

```
import {createClient, AuthType} from 'webdav/dist/node';

/// ...
const client = createClient('https://dav.jianguoyun.com/dav/', {
        authType: AuthType.Password,
        username: 'xxx',
        password: 'xxx',
 });
await client.getDirectoryContents('/');
```
but it still not make sense with with several error messages like *unable to resolve module stream or posix-path* or something..

---

Can you provide **a guide** on how to setup this lib in react-native, or a **minimal respository** about integrating this lib in react-native project? 😭

Looking for your help and thank you for your awesome work.

**Comment by perry-mitchell** [comment]
Hello! Sorry for the inconvenience. I do actually use this library on react native (buttercup-mobile), but I don't actively maintain documentation for using it there. I'll try to find a reference there for you.

In the meantime: definitely avoid using the node import, that won't work. Can you try using the web version directly?

```
import { createClient } from "webdav/web";
```

**Comment by maotoumao** [comment]
Thank you for your reply!


I tried the web version:

![组合 2](https://github.com/perry-mitchell/webdav-client/assets/31655147/019f8d23-5708-41c1-b671-3c60cccbee61)


but the result is still the same:

![image](https://github.com/perry-mitchell/webdav-client/assets/31655147/db2d507d-1076-4ae0-b4b6-61e5fb7caa92)


I checked the error stack:

![image](https://github.com/perry-mitchell/webdav-client/assets/31655147/ed6068c1-3a7a-4b87-8bfd-7b0480ffd3ba)


and it seems that the error is raised by **decodeHTMLEntities** function, because there is no *document* variable in react-native environment.

![image](https://github.com/perry-mitchell/webdav-client/assets/31655147/ba58edbc-7847-453b-9185-0148aee0f377)

---

Should I import any polyfill or make some extra config?

**Comment by SakiiCode** [comment]
I am having the same issue. Is there any update on this?

**Comment by perry-mitchell** [comment]
Sorry, no update yet. I'm working on a new major version for the client at the moment.. I'll try to include a React-native-specific fix for this.

**Comment by maotoumao** [comment]
> I am having the same issue. Is there any update on this?

I [forked this repository](https://github.com/maotoumao/webdav-client) and made some changes to adapt React Native as a temporary solution.

The [changes](https://github.com/maotoumao/webdav-client/commit/2869af07b29d1607280a9174e923f433605a598c) are   mainly on using `he.decode(text)` instead of creating a `textarea` element (which causes the error described in this topic), and mark `he` as peerDependencies and external package. 

For anyone having the same issue, you can install `webdav` by following commands and use the lib as normal:
```bash
npm install https://github.com/maotoumao/webdav-client#release
npm install he
```

Please note that this fork is only a **temporary solution** based on the `5.3.1` version of `webdav`. It's really NOT a good solution, but it works :)

Looking forward to the official fix by @perry-mitchell.

**Comment by perry-mitchell** [comment]
I avoided adding `he` for the web version because, well, the web supports this natively. `he` is also a massive library, and bundling that would be wasteful. I'll try to get to this asap.
