### ISSUE TITLE
React-Native import fails

### ISSUE THREAD

**Issue by FengFuLiu** [perry-mitchell/webdav-client#366]
show error when i  import webdav/react-native

**Comment by FengFuLiu** [comment]
![4ba2cb8df2eff760a90d1daac8cec9d2](https://github.com/perry-mitchell/webdav-client/assets/22019735/f139e598-2ed6-4d38-9338-948cc8f9b15b)

**Comment by ihwf** [comment]
use from `webdav/dist/web` is work😂

**Comment by perry-mitchell** [comment]
It's actually `import {} from "webdav/react-native", no need for the dist. And even just importing from `"webdav"` should work as we have the `react-native` entry in the package.json. I'm using [that here](https://github.com/buttercup/buttercup-mobile/blob/4587962d4b680bf346674683dbddcc033dff08fd/source/library/webdav.ts#L1).

**Comment by ihwf** [comment]
from "webdav" not work, throw this
![image](https://github.com/perry-mitchell/webdav-client/assets/17941662/88f1befa-a9dc-408e-b1e3-74a68719f8d4)
and if from "webdav/react-native", it throw `Unable to resolve "webdav/react-native"`
BTW: use `"react-native": "0.73.4", "webdav": "^5.5.0"`

**Comment by Lucas-vdr-Horst** [comment]
I have the same problem. Were you able to solve this?

**Comment by perry-mitchell** [comment]
All the issues I'm currently seeing here point to the fact that this library uses references on both sides (node/web) that simply won't work on RN. On the web side we have document references, and on the node side we have http agent references. Neither will ever work.

I'm trying to figure out how to bypass this issue now.

**Comment by perry-mitchell** [comment]
Please see updated docs: https://github.com/perry-mitchell/webdav-client?tab=readme-ov-file#react-native-support
