### ISSUE TITLE
pop error when connect to webdav server with http address

### ISSUE THREAD

**Issue by JackZhen1324** [perry-mitchell/webdav-client#377]
I was trying to connect to webav server on my react native app, I found out it pop error every time when I put http address. I dont know if it's a bug or not, anyone could tell me how to solve this issue. btw, it works fine with https 
<img width="362" alt="Screenshot 2024-07-05 at 6 24 27 PM" src="https://github.com/perry-mitchell/webdav-client/assets/17266116/491846fa-be14-4c02-bd78-babbd53386ee">

**Comment by perry-mitchell** [comment]
This is a react-native limitation - it's standard RN networking but I don't recall how to get around it.. Bit of searching regarding HTTP requests should yield results.

Closing as not related to this library.
