### ISSUE TITLE
minimatch 10.0.1 not suportet Node 18

### ISSUE THREAD

**Issue by simatec** [perry-mitchell/webdav-client#382]
Can you please downgrade the minimatch 10.0.1 version again.
With the update to 10.0.1 Webdav no longer supports Node 18, which is still not End of Life and should be supported.

Thx ;)

**Comment by perry-mitchell** [comment]
Hi! Regardless of minimatch's node support, which I probably missed as you said - the [tests still pass](https://github.com/perry-mitchell/webdav-client/blob/03fa8f2fbd9b1a0ad99ccb0ca1fd7e73c2c2c8c5/test/node/operations/getDirectoryContents.spec.ts#L277): https://github.com/perry-mitchell/webdav-client/actions/runs/10215635123

Which shouldn't be the case if it didn't support node 18 (specifically [this run](https://github.com/perry-mitchell/webdav-client/actions/runs/10215635123/job/28265450411).

**Comment by perry-mitchell** [comment]
Seems it's just an engine requirement, so not major. I'll downgrade all the same, for now.

**Comment by simatec** [comment]
Thanks for the adjustments and for your work
