### ISSUE TITLE
[Feature] Upload entire directory

### ISSUE THREAD

**Issue by perry-mitchell** [perry-mitchell/webdav-client#43]
Add ability to upload an entire directory.

**Comment by perry-mitchell** [comment]
This should be in a separate repo.

**Comment by huangganggui** [comment]
@perry-mitchell  is there any repo do this？

**Comment by perry-mitchell** [comment]
Not that I know of. I've considered building one for ages but haven't had time.

Either I'll get to it soon or someone else will; and if they use this library I'd happily collaborate with them to keep the support strong.

**Comment by huangganggui** [comment]
@perry-mitchell 
I think it may be not too difficult. based on client, create dir and upload files recursively.
