### ISSUE TITLE
Encode & decode URI

### ISSUE THREAD

**Issue by kistora** [perry-mitchell/webdav-client#47]
I have an issue with your webdav-client.
### Config
- NodeJS v.8.0.0
- Webdav-client v0.10.0
- OwnCloud v10.0.2.1 as webdav server
### Description
- I want to get the content of the following directory: `/têst/`
- I use the getDirectoryMethod like: `client.getDirectoryContents("/têst");`
- But i have an Internal Server Error (500)
### Proposed fix
The problem is that the URI is not encoded before sending the request using fetch.
So I transform the call of getDirectoryMethod like:  `client.getDirectoryContents(encodeURI("/têst"));`
## Issue 2
With the fix of issue 1, another issue appears:
### Description
- I want to get the content of the following directory: `/têst/`
- I use the getDirectoryMethod like: `client.getDirectoryContents(encodeURI("/têst"));`
- But the getDirectoryMethod return an empty array even if the folder is not.

So, the issue is that the path is not encoded before fetching. But the path is directly used to match the filename in the parser.
I think that the webdav module should handle pre-encoded path, so here is the proposed fix:
### Proposed fix
You have to add this following line: `dirPath = decodeURI(dirPath);` before line 64 in the file `parse.js`.

Thank you for your work.

**Comment by perry-mitchell** [comment]
Thanks @kistora. I think this could be easily added. Would be great to have a failing test added for it. I'll try to get to it soon if no on else does first.

**Comment by kistora** [comment]
@perry-mitchell So I've done it. #48
