### ISSUE TITLE
getDirectoryContents filename parse bug

### ISSUE THREAD

**Issue by zh99998** [perry-mitchell/webdav-client#54]
when directory name is included in base url, getDirectoryContents will return wrong result.

for example I have requested base url `http://.../storage/test1` and request to list `/te` directory
in my server it is an empty directory, so empty array is expected, but got `['/test1/te']`

in `parse.js` processDirectoryResultFilename
```js
var pos = resultFilename.indexOf(dirPath);
```

I think bug is here.
`'/storage/test1/te'.indexOf('/te')` will got 8, which expected 14.

maybe we should save base url when creating client, or... does lastIndexOf() works?

**Comment by zh99998** [comment]
well lastIndexOf not works.

seems we have to store base url from create client
if I request "/", base url is "/storage/test1", and there is one `test2` directory inner `test1`
server will response 2 item `/storage/test1/`, `/storage/test1/test2/`
simple string analysis could never tell apart which is base href and which is directory.

**Comment by perry-mitchell** [comment]
Ah good catch @zh99998 that's definitely a bad issue..

> seems we have to store base url from create client

Yeah it looks like we need a bit of an overhaul there..

**Comment by perry-mitchell** [comment]
After looking at the code, this looks like a deeper architectural issue.. I haven't considered webdav servers and subdirectory hosting. If the server is hosted on a sub directory then these pathing issues can be found easily. Need to consider what the best way forward is..
