### ISSUE TITLE
Update code style -> const/let

### ISSUE THREAD

**Issue by perry-mitchell** [perry-mitchell/webdav-client#56]
Use scoped declarations to neaten the library.

**Comment by zh99998** [comment]
webstorm & eslint -> fix current file -> done.

btw I even think we should move to TypeScript.

**Comment by perry-mitchell** [comment]
Thanks for submitting a PR, I left some comments.

> btw I even think we should move to TypeScript.

I prefer working with Javascript, as it's much simpler. Also, it means that this library can be directly used elsewhere in other node projects with no transpilation.

**Comment by zh99998** [comment]
I have done it as your request.
added "use strict" in all js file and
removed all comma statement in const declare

now CI passed.

BUT I STILL THINK IT'S STUPID.

with a transpiler, we can use all new features without any worry and just specific `target:es5` then it works in nearly all version of node.js and *browsers* .

**Comment by perry-mitchell** [comment]
> I have done it as your request

Thanks! I'll check into it later today, as I'm at work currently.

> BUT I STILL THINK IT'S STUPID

I'm sorry you feel that way.

> with a transpiler, we can use all new features without any worry and just specific target:es5 then it works in nearly all version of node.js and browsers

All of that is _needlessly_ complicated. At some stage I may add a browser version to this project, but I don't want necessary build steps before it's even usable in its primary target platform: Node. Typescript is awkward and adds little value imo.

**Comment by perry-mitchell** [comment]
@zh99998 I merged your PR - Thanks for contributing!
