### ISSUE TITLE
decode url in filename

### ISSUE THREAD

**Issue by zh99998** [perry-mitchell/webdav-client#64]
I get some `%2b` in my filename, actually filename is `+`

**Comment by perry-mitchell** [comment]
@zh99998 That's interesting, though I guess logical. We added URI encoding/decoding to support non-ascii characters (like other alphabets), and I guess this feature is working incorrectly in this case.

What do you mean by getting it in your filename? Is it when you create a new file or when you try to fetch it?

**Comment by zh99998** [comment]
in result of `getDirectoryContents()`

**Comment by perry-mitchell** [comment]
I haven't been able to reproduce this, and the [decode line here](https://github.com/perry-mitchell/webdav-client/blob/master/source/interface/directoryContents.js#L59) should take care of this. We can reopen if necessary.
