### ISSUE TITLE
SSL: Allow certificate specification or option to disable strict SSL checking

### ISSUE THREAD

**Issue by perry-mitchell** [perry-mitchell/webdav-client#67]
Currently there is no way to bypass the strict SSL checking in the library, meaning that websites using self-signed certificates cannot be connected to. One (or both) of the following options should be undertaken:

 1. Add an option to allow for the disabling of strict SSL checking
 2. Add an option to allow for the specification of certifcates

**Comment by Jakobud** [comment]
My fix for #6 involves passing in an https agent to `node-fetch` via `webdav-client` options. When i get this implemented it should kill 2 birds with 1 stone here, as you can pass `rejectUnauthorized: false` to the `httpsAgent` object.

**Comment by kuehnelbs** [comment]
As @Jakobud mentioned in #6 the easiest way will be bypassing the agent . I hat a closer look to this problem trying to fix [No HTTPS connection to unsecure server](https://github.com/kuehnelbs/node-red-contrib-nextcloud/issues/1) and came to the same solution:

```
    const addOption = {
        'agent': new https.Agent({ rejectUnauthorized: false })
    }
    client.getDirectoryContents(remotePath, addOption)
        .then(function (contents) {
            // ...
        }, function (error) {
            // ...
        })
```

```
    function getDirectoryContents(remotePathRaw, options) {
        // ...
        var fetchOptions = {
            method: "PROPFIND",
            headers: merge({
                Depth: 1
            }, options.headers),
            agent: merge({
                Depth: 1
            }, options.agent)
        };
        //...
      }
```
This fixed my problem to access a nextcloud server using a self signed cert

**Comment by perry-mitchell** [comment]
This has already been completed by @Jakobud, and will be released in the next version 👍

**Comment by perry-mitchell** [comment]
You're right @perrinjerome - This should have been closed. Thanks!
