### ISSUE TITLE
Get additional file information

### ISSUE THREAD

**Issue by EsSpricht** [perry-mitchell/webdav-client#70]
getDirectoryContents(remotePath [, options]) returns the content of a folder. It allows me to specify some additional request options for the server. Is it also possible for the server to add additional file information to the response?

Let's say an extra file stat like a called tracker:

{
    "filename": "/image.jpg",
    "basename": "image.jpg",
    "lastmod": "Sun, 13 Mar 2016 04:23:32 GMT",
    "size": 42497,
    "type": "file",
    "mime": "image/jpeg",
    "accessed": "23"
}

the would give me the information about how many times this file was called (23x). 
Is this possible?

**Comment by perry-mitchell** [comment]
It's possible to return any of the headers that the server responds with, but currently not in the API provided by this library. An update is planned to change the API so that extra properties (like headers) can be returned.

**Comment by perry-mitchell** [comment]
The issue I mentioned is actually #16, so I'll close this one as I feel that it's a duplicate.
