### ISSUE TITLE
`createWriteStream` and Nextcloud

### ISSUE THREAD

**Issue by floriansimon1** [perry-mitchell/webdav-client#72]
Hi,

First, thanks for the hard work you've put into this!

I have a question: is there anything special that I have to do to close the write stream? Because when I tried to run `createWriteStream` after a successful upload, Nextcloud returns a `405 Method Not Allowed` to my face, so I thought that maybe I needed to do some ceremony to finish the upload?

Thanks in advance

**Comment by floriansimon1** [comment]
`webdav-client` is fine. After debugging, I noticed that I got that error because I was trying to create a directory that already existed right before writing the file.

**Comment by perry-mitchell** [comment]
> First, thanks for the hard work you've put into this!

Thanks @floriansimon1 !
