### ISSUE TITLE
Uncaught (in promise) TypeError: res.buffer is not a function

### ISSUE THREAD

**Issue by subdavis** [perry-mitchell/webdav-client#74]
```
getFile.js:10 Uncaught (in promise) TypeError: res.buffer is not a function
    at getFile.js:10
    at <anonymous>
(anonymous) @ getFile.js:10
...
```

I'm seeing this in Chrome Version 64.0.3282.167 (Official Build) (64-bit) using the following snippet compiled by webpack and babel.

```javascript
const createClient = require("webdav");
...
let client = createClient(url, username, password)
createClient.setFetchMethod(window.fetch)
return client.getFileContents(PATH).then(bin=> {
	console.log(bin)
})
```

Seems like a fairly common use case.  Did I miss something?

**Comment by subdavis** [comment]
## Problem

After a little more research, this certainly looks like a bug.

The `window.fetch` api returns a `Response` which implements `Body` as documented [here](https://developer.mozilla.org/en-US/docs/Web/API/Body)

`Body` has no `buffer()` method like node-fetch, but instead a `arrayBuffer()` method for the same function.  I checked and it looks like in version 2.0 of node-fetch, `arrayBuffer()` is implemented for just this exact use case: where we want compatibility on the browser and in nodejs:

https://github.com/bitinn/node-fetch/issues/51

## Solution:

Looks like changing to `arrayBuffer` and upgrading node-fetch will do the trick.

**Comment by perry-mitchell** [comment]
This has been changed. Just need to update the tests to pass and it'll be good to go 👍
