### ISSUE TITLE
getFileContents downloads empty image file

### ISSUE THREAD

**Issue by Jakobud** [perry-mitchell/webdav-client#79]
I have a very basic setup:

```
client.getDirectoryContents('default/images')
  .then(data => {
    console.log(data)
    return client.getFileContents('default/images/myFile.png')
  }).then(data => {
    fs.writeFileSync('./myImage.png', data)
  })
  .catch(err => {
    console.error(`${err}`)
  })
```

This code is really simple. It first prints out the directory contents, which verifies that the `myFile.png` does exist:

```
[{ filename: '/default/images/myFile.png',
    basename: 'myFile.png',
    lastmod: 'Thu, 25 Jan 2018 21:40:45 GMT',
    size: 109484,
    type: 'file',
    mime: 'image/png' }]
```

Then I downloads the file and writes it locally to `myImage.png`. After the script is done, the resulting `myImage.png` is only 20 bytes and is not a valid image file. Cannot open it. It should be about 110KB.

What am I missing here? I am absolutely sure I have full read/write permissions to this webdav server. I can access it using Cyberduck and upload/download images all day long without issue. I can also do stuff like access/read directories, create new directories, etc.

I'm not sure how to figure out what is going wrong. There is no error that is caught from the Promise. I don't get any local file writing errors.

Can you point me in the right direction? Is this a bug? Or am I doing something wrong?

**Comment by Jakobud** [comment]
After some more investigation it looks like the file being written was just an ascii file with contents:

```
ArrayBuffer { byteLength: 109484 }
```

Okay so it appears your library isn't actually converting the contents from the webdav server into a writable buffer. I looked into your tests and sure enough you are using the `arraybuffer-to-buffer` library. I added it in and it worked fine now:

```
fs.writeFileSync('./myImage.png', arrayBufferToBuffer(data))
```

The problem is, this is completely missing from your documentation. Like it's not there at all. Is that on purpose? Also why don't you just have your library do this automatically instead of asking users to figure this dependency out and have to do it anyways?

**Comment by perry-mitchell** [comment]
Hi @Jakobud - this is indeed a regression, due to #74. Of course an array buffer is fine in the browser but not in node for use cases like this - I'll release a fix shortly.

**Comment by perry-mitchell** [comment]
@Jakobud Version 1.3.0 has the new functionality. Thanks for reporting!

**Comment by Jakobud** [comment]
Ah okay so it was a bug. Your tests made it look like you actually intentionally needed to use the arraybuffer-to-buffer library. Glad I could help. Thanks!
