### ISSUE TITLE
[SUPPORT] Not able to get the folder contents.

### ISSUE THREAD

**Issue by voidapps** [perry-mitchell/webdav-client#85]
Hi, 

I need some help with an issue im facing. Not sure if this is my own wrong doing or this is a bug but I cant get this to work.

Im trying to get the file contents of a folder in a Websphere Virtual Portal. This is my code:

```
const client = createClient(
  'https://example.com/dav/fs-type1/themes/themeName',
  'username@example.com',
  'password'
)

client.getDirectoryContents('/modules')
  .then(contents => console.log(JSON.stringify(contents, null, 4)))
  .catch(err => console.error(err))
```

So when this code executes I get the following error:
`TypeError: Cannot read property 'filter' of undefined`

I tried intercepting the result on the getDirectoryContents function in the source and log the results which does return the correct files in the modules folder.

Thanks for the help!

**Comment by perry-mitchell** [comment]
Would it be possible to share the response you get? Of course you can obscure file names etc..

Also, could you please share the exact location of where you’re logging from.

**Comment by voidapps** [comment]
Hi Perry, 

Thanks for the response, do you mean sharing the response from my console.log in the source code? I'll supply that tomorrow as Im not at work currently. 

Im logging from: ` webdav-client/source/interface/directoryContents.js` line 45: 
```
console.log(result)
```

Thanks a lot!

**Comment by perry-mitchell** [comment]
Thanks, and yes, if you could share the output. I could perhaps use that to debug why it’s failing.

**Comment by voidapps** [comment]
I zipped a json file (Github doesnt allow json attachments...) with the results of the log described before.
[result.json.zip](https://github.com/perry-mitchell/webdav-client/files/1832772/result.json.zip)

**Comment by perry-mitchell** [comment]
Apologies for the delay @voidapps - Unfortunately still no good news. I don't have a lot of time right now to work on larger tasks like this. I'd be more than happy to accept a PR for this issue, but otherwise I probably won't get around to it anytime soon.

**Comment by dgtlmoon** [comment]
Any news? small bump :)

**Comment by perry-mitchell** [comment]
Closing as this is out of date.
