### ISSUE TITLE
README out of date

### ISSUE THREAD

**Issue by kieranongh** [perry-mitchell/webdav-client#90]
I recently refreshed my npm modules, which included an updated version of `webdav-client`. I found that my code was having trouble parsing JSON from what was returned in a `getFileContents()` call.

It turns out, the option "text" was not being recognised, and it would default to "binary" when it went to make the HTTP GET. After inspecting the code, the options was looking for an object syntax, much like other webdav interface functions (putFileContents, etc). I had still been using the syntax provided on the README.

I've since made a pull request updating the README to show the new syntax for specifying options for `getFileContents`

**Comment by perry-mitchell** [comment]
I suppose that this has been taken care of due to #89 having been merged? We can of course reopen if there are other discrepancies.
