### ISSUE TITLE
client.getFileStream is not a function

### ISSUE THREAD

**Issue by Nikola-Andreev** [perry-mitchell/webdav-client#97]
Hello.
Sorry but i can't understand how to use the  **client.getFileStream** method. Can someone provide me a working example because this from documentation throws TypeError: client.getFileStream is not a function.
```
var fs = require("fs");
client
    .getFileStream("/test/image.png")
    .then(function(imageStream) {
        imageStream.pipe(fs.createWriteStream("./image.png"));
    });
```
I understand that i need to **createReadStream** first, but this method returns me just an object and i don't know what to do with it.

**Comment by perry-mitchell** [comment]
Hi @Nikola-Andreev - The `getFileStream` method was removed, I believe.. possibly in [v1.0](https://github.com/perry-mitchell/webdav-client/blob/master/CHANGELOG.md#100-rc1). The docs are out of date - I'll fix that now.

You probably want `createReadStream`:

```javascript
const fs = require("fs");

const rs = client.createReadStream("/test/image.png");
rs.pipe(fs.createWriteStream("./image.png"));
```

**Comment by Nikola-Andreev** [comment]
Yes, i solved the problem with pipe. Thanks
